
/**
 * GitHub API Integration Utility
 */

export interface GitHubSettings {
  token: string;
  repo: string;
  autoPush: boolean;
}

const STORAGE_KEY = 'github_sync_settings';

export function getGitHubSettings(): GitHubSettings | null {
  const saved = localStorage.getItem(STORAGE_KEY);
  if (!saved) return null;
  try {
    return JSON.parse(saved);
  } catch {
    return null;
  }
}

export function saveGitHubSettings(settings: GitHubSettings) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(settings));
}


/**
 * Checks if a GitHub repository exists.
 */
export async function checkGitHubRepoExists(token: string, repo: string): Promise<boolean> {
  try {
    const userRes = await fetch('https://api.github.com/user', {
      headers: { Authorization: `token ${token}` }
    });
    if (!userRes.ok) return false;
    const user = await userRes.json();
    const owner = user.login;

    const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
      headers: { Authorization: `token ${token}` }
    });
    return repoRes.ok;
  } catch {
    return false;
  }
}

/**
 * Creates a new GitHub repository.
 */
export async function createGitHubRepo(token: string, repo: string): Promise<{ success: boolean; error?: string }> {
  try {
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `token ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: repo,
        description: 'Solutions to DSA problems generated by CodeCompanion AI',
        private: false,
        auto_init: true
      })
    });

    if (createRes.status === 422) {
      return { success: false, error: 'Repository already exists or name is invalid.' };
    }

    if (!createRes.ok) {
      const err = await createRes.json();
      throw new Error(err.message || 'Failed to create repository');
    }

    return { success: true };
  } catch (error: any) {
    console.error('GitHub Create Repo Error:', error);
    return { success: false, error: error.message };
  }
}

/**
 * Pushes a file to a GitHub repository.
 * If the file exists, it updates it. If not, it creates it.
 */
export async function pushFileToGitHub(
  token: string,
  repo: string,
  path: string,
  content: string,
  commitMessage: string
): Promise<{ success: boolean; url?: string; error?: string }> {
  try {
    // 1. Get authenticated user info
    const userRes = await fetch('https://api.github.com/user', {
      headers: { Authorization: `token ${token}` }
    });
    
    if (!userRes.ok) throw new Error('Invalid GitHub token');
    const user = await userRes.json();
    const owner = user.login;

    // 2. Check if repository exists
    const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
      headers: { Authorization: `token ${token}` }
    });

    if (repoRes.status === 404) {
      // Repository not found, try to create it
      const createResult = await createGitHubRepo(token, repo);
      if (!createResult.success) {
        throw new Error(createResult.error || 'Failed to create repository');
      }
      // Wait a bit for GitHub to initialize the repo
      await new Promise(resolve => setTimeout(resolve, 2500));
    } else if (!repoRes.ok) {
      throw new Error('Failed to access repository');
    }

    // 3. Check if file exists to get its SHA
    const fileRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
      headers: { Authorization: `token ${token}` }
    });

    let sha: string | undefined;
    if (fileRes.ok) {
      const fileData = await fileRes.json();
      sha = fileData.sha;
    }

    // 4. Create or update the file
    // GitHub API expects content to be base64 encoded. 
    // btoa() works for ASCII, but for UTF-8 (which code might be), we should use a more robust way.
    const base64Content = btoa(unescape(encodeURIComponent(content)));

    const pushRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
      method: 'PUT',
      headers: {
        Authorization: `token ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        message: commitMessage,
        content: base64Content,
        sha: sha // Required if updating existing file
      })
    });

    if (!pushRes.ok) {
      const err = await pushRes.json();
      throw new Error(err.message || 'Failed to push file');
    }

    const result = await pushRes.json();
    return { 
      success: true, 
      url: result.content.html_url 
    };

  } catch (error: any) {
    console.error('GitHub Push Error:', error);
    return { success: false, error: error.message };
  }
}

