import { type RoadmapProblem, type RoadmapTopic } from './striver-roadmap-data';

export const LEETCODE_TOP150_ROADMAP: RoadmapTopic[] = [
  {
    name: 'Array / String',
    icon: '📊',
    color: 'hsl(220, 70%, 55%)',
    problems: [
      { key: 'lc-as-1', title: 'Merge Sorted Array', difficulty: 'Easy' },
      { key: 'lc-as-2', title: 'Remove Element', difficulty: 'Easy' },
      { key: 'lc-as-3', title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy' },
      { key: 'lc-as-4', title: 'Remove Duplicates from Sorted Array II', difficulty: 'Medium' },
      { key: 'lc-as-5', title: 'Majority Element', difficulty: 'Easy' },
      { key: 'lc-as-6', title: 'Rotate Array', difficulty: 'Medium' },
      { key: 'lc-as-7', title: 'Best Time to Buy and Sell Stock', difficulty: 'Easy' },
      { key: 'lc-as-8', title: 'Best Time to Buy and Sell Stock II', difficulty: 'Medium' },
      { key: 'lc-as-9', title: 'Jump Game', difficulty: 'Medium' },
      { key: 'lc-as-10', title: 'Jump Game II', difficulty: 'Medium' },
      { key: 'lc-as-11', title: 'H-Index', difficulty: 'Medium' },
      { key: 'lc-as-12', title: 'Insert Delete GetRandom O(1)', difficulty: 'Medium' },
      { key: 'lc-as-13', title: 'Product of Array Except Self', difficulty: 'Medium' },
      { key: 'lc-as-14', title: 'Gas Station', difficulty: 'Medium' },
      { key: 'lc-as-15', title: 'Candy', difficulty: 'Hard' },
      { key: 'lc-as-16', title: 'Trapping Rain Water', difficulty: 'Hard' },
      { key: 'lc-as-17', title: 'Roman to Integer', difficulty: 'Easy' },
      { key: 'lc-as-18', title: 'Integer to Roman', difficulty: 'Medium' },
      { key: 'lc-as-19', title: 'Length of Last Word', difficulty: 'Easy' },
      { key: 'lc-as-20', title: 'Longest Common Prefix', difficulty: 'Easy' },
      { key: 'lc-as-21', title: 'Reverse Words in a String', difficulty: 'Medium' },
      { key: 'lc-as-22', title: 'Zigzag Conversion', difficulty: 'Medium' },
      { key: 'lc-as-23', title: 'Find the Index of the First Occurrence', difficulty: 'Easy' },
      { key: 'lc-as-24', title: 'Text Justification', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Two Pointers',
    icon: '👆',
    color: 'hsl(180, 60%, 45%)',
    problems: [
      { key: 'lc-tp-1', title: 'Valid Palindrome', difficulty: 'Easy' },
      { key: 'lc-tp-2', title: 'Is Subsequence', difficulty: 'Easy' },
      { key: 'lc-tp-3', title: 'Two Sum II - Input Array Is Sorted', difficulty: 'Medium' },
      { key: 'lc-tp-4', title: 'Container With Most Water', difficulty: 'Medium' },
      { key: 'lc-tp-5', title: '3Sum', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Sliding Window',
    icon: '🪟',
    color: 'hsl(200, 70%, 50%)',
    problems: [
      { key: 'lc-sw-1', title: 'Minimum Size Subarray Sum', difficulty: 'Medium' },
      { key: 'lc-sw-2', title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium' },
      { key: 'lc-sw-3', title: 'Substring with Concatenation of All Words', difficulty: 'Hard' },
      { key: 'lc-sw-4', title: 'Minimum Window Substring', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Matrix',
    icon: '🔢',
    color: 'hsl(90, 50%, 50%)',
    problems: [
      { key: 'lc-mx-1', title: 'Valid Sudoku', difficulty: 'Medium' },
      { key: 'lc-mx-2', title: 'Spiral Matrix', difficulty: 'Medium' },
      { key: 'lc-mx-3', title: 'Rotate Image', difficulty: 'Medium' },
      { key: 'lc-mx-4', title: 'Set Matrix Zeroes', difficulty: 'Medium' },
      { key: 'lc-mx-5', title: 'Game of Life', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Hashmap',
    icon: '#️⃣',
    color: 'hsl(35, 80%, 55%)',
    problems: [
      { key: 'lc-hm-1', title: 'Ransom Note', difficulty: 'Easy' },
      { key: 'lc-hm-2', title: 'Isomorphic Strings', difficulty: 'Easy' },
      { key: 'lc-hm-3', title: 'Word Pattern', difficulty: 'Easy' },
      { key: 'lc-hm-4', title: 'Valid Anagram', difficulty: 'Easy' },
      { key: 'lc-hm-5', title: 'Group Anagrams', difficulty: 'Medium' },
      { key: 'lc-hm-6', title: 'Two Sum', difficulty: 'Easy' },
      { key: 'lc-hm-7', title: 'Happy Number', difficulty: 'Easy' },
      { key: 'lc-hm-8', title: 'Contains Duplicate II', difficulty: 'Easy' },
      { key: 'lc-hm-9', title: 'Longest Consecutive Sequence', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Intervals',
    icon: '📏',
    color: 'hsl(15, 70%, 55%)',
    problems: [
      { key: 'lc-iv-1', title: 'Summary Ranges', difficulty: 'Easy' },
      { key: 'lc-iv-2', title: 'Merge Intervals', difficulty: 'Medium' },
      { key: 'lc-iv-3', title: 'Insert Interval', difficulty: 'Medium' },
      { key: 'lc-iv-4', title: 'Minimum Number of Arrows to Burst Balloons', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Stack',
    icon: '📚',
    color: 'hsl(30, 80%, 55%)',
    problems: [
      { key: 'lc-sk-1', title: 'Valid Parentheses', difficulty: 'Easy' },
      { key: 'lc-sk-2', title: 'Simplify Path', difficulty: 'Medium' },
      { key: 'lc-sk-3', title: 'Min Stack', difficulty: 'Medium' },
      { key: 'lc-sk-4', title: 'Evaluate Reverse Polish Notation', difficulty: 'Medium' },
      { key: 'lc-sk-5', title: 'Basic Calculator', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Linked List',
    icon: '🔗',
    color: 'hsl(150, 70%, 45%)',
    problems: [
      { key: 'lc-ll-1', title: 'Linked List Cycle', difficulty: 'Easy' },
      { key: 'lc-ll-2', title: 'Add Two Numbers', difficulty: 'Medium' },
      { key: 'lc-ll-3', title: 'Merge Two Sorted Lists', difficulty: 'Easy' },
      { key: 'lc-ll-4', title: 'Copy List with Random Pointer', difficulty: 'Medium' },
      { key: 'lc-ll-5', title: 'Reverse Linked List II', difficulty: 'Medium' },
      { key: 'lc-ll-6', title: 'Reverse Nodes in K-Group', difficulty: 'Hard' },
      { key: 'lc-ll-7', title: 'Remove Nth Node From End of List', difficulty: 'Medium' },
      { key: 'lc-ll-8', title: 'Remove Duplicates from Sorted List II', difficulty: 'Medium' },
      { key: 'lc-ll-9', title: 'Rotate List', difficulty: 'Medium' },
      { key: 'lc-ll-10', title: 'Partition List', difficulty: 'Medium' },
      { key: 'lc-ll-11', title: 'LRU Cache', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Binary Tree General',
    icon: '🌳',
    color: 'hsl(120, 50%, 45%)',
    problems: [
      { key: 'lc-bt-1', title: 'Maximum Depth of Binary Tree', difficulty: 'Easy' },
      { key: 'lc-bt-2', title: 'Same Tree', difficulty: 'Easy' },
      { key: 'lc-bt-3', title: 'Invert Binary Tree', difficulty: 'Easy' },
      { key: 'lc-bt-4', title: 'Symmetric Tree', difficulty: 'Easy' },
      { key: 'lc-bt-5', title: 'Construct Binary Tree from Preorder and Inorder', difficulty: 'Medium' },
      { key: 'lc-bt-6', title: 'Construct Binary Tree from Inorder and Postorder', difficulty: 'Medium' },
      { key: 'lc-bt-7', title: 'Populating Next Right Pointers in Each Node II', difficulty: 'Medium' },
      { key: 'lc-bt-8', title: 'Flatten Binary Tree to Linked List', difficulty: 'Medium' },
      { key: 'lc-bt-9', title: 'Path Sum', difficulty: 'Easy' },
      { key: 'lc-bt-10', title: 'Sum Root to Leaf Numbers', difficulty: 'Medium' },
      { key: 'lc-bt-11', title: 'Binary Tree Maximum Path Sum', difficulty: 'Hard' },
      { key: 'lc-bt-12', title: 'Binary Search Tree Iterator', difficulty: 'Medium' },
      { key: 'lc-bt-13', title: 'Count Complete Tree Nodes', difficulty: 'Easy' },
      { key: 'lc-bt-14', title: 'Lowest Common Ancestor of a Binary Tree', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Binary Tree BFS',
    icon: '🌊',
    color: 'hsl(195, 70%, 50%)',
    problems: [
      { key: 'lc-bfs-1', title: 'Binary Tree Right Side View', difficulty: 'Medium' },
      { key: 'lc-bfs-2', title: 'Average of Levels in Binary Tree', difficulty: 'Easy' },
      { key: 'lc-bfs-3', title: 'Binary Tree Level Order Traversal', difficulty: 'Medium' },
      { key: 'lc-bfs-4', title: 'Binary Tree Zigzag Level Order Traversal', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Binary Search Tree',
    icon: '🔎',
    color: 'hsl(270, 50%, 55%)',
    problems: [
      { key: 'lc-bst-1', title: 'Minimum Absolute Difference in BST', difficulty: 'Easy' },
      { key: 'lc-bst-2', title: 'Kth Smallest Element in a BST', difficulty: 'Medium' },
      { key: 'lc-bst-3', title: 'Validate Binary Search Tree', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Graph General',
    icon: '🕸️',
    color: 'hsl(160, 60%, 45%)',
    problems: [
      { key: 'lc-gg-1', title: 'Number of Islands', difficulty: 'Medium' },
      { key: 'lc-gg-2', title: 'Surrounded Regions', difficulty: 'Medium' },
      { key: 'lc-gg-3', title: 'Clone Graph', difficulty: 'Medium' },
      { key: 'lc-gg-4', title: 'Evaluate Division', difficulty: 'Medium' },
      { key: 'lc-gg-5', title: 'Course Schedule', difficulty: 'Medium' },
      { key: 'lc-gg-6', title: 'Course Schedule II', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Graph BFS',
    icon: '🌐',
    color: 'hsl(175, 60%, 45%)',
    problems: [
      { key: 'lc-gbfs-1', title: 'Snakes and Ladders', difficulty: 'Medium' },
      { key: 'lc-gbfs-2', title: 'Minimum Genetic Mutation', difficulty: 'Medium' },
      { key: 'lc-gbfs-3', title: 'Word Ladder', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Trie',
    icon: '🔤',
    color: 'hsl(290, 60%, 55%)',
    problems: [
      { key: 'lc-tr-1', title: 'Implement Trie (Prefix Tree)', difficulty: 'Medium' },
      { key: 'lc-tr-2', title: 'Design Add and Search Words Data Structure', difficulty: 'Medium' },
      { key: 'lc-tr-3', title: 'Word Search II', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Backtracking',
    icon: '🔄',
    color: 'hsl(340, 70%, 55%)',
    problems: [
      { key: 'lc-bk-1', title: 'Letter Combinations of a Phone Number', difficulty: 'Medium' },
      { key: 'lc-bk-2', title: 'Combinations', difficulty: 'Medium' },
      { key: 'lc-bk-3', title: 'Permutations', difficulty: 'Medium' },
      { key: 'lc-bk-4', title: 'Combination Sum', difficulty: 'Medium' },
      { key: 'lc-bk-5', title: 'N-Queens II', difficulty: 'Hard' },
      { key: 'lc-bk-6', title: 'Generate Parentheses', difficulty: 'Medium' },
      { key: 'lc-bk-7', title: 'Word Search', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Divide & Conquer',
    icon: '✂️',
    color: 'hsl(330, 60%, 50%)',
    problems: [
      { key: 'lc-dc-1', title: 'Convert Sorted Array to Binary Search Tree', difficulty: 'Easy' },
      { key: 'lc-dc-2', title: 'Sort List', difficulty: 'Medium' },
      { key: 'lc-dc-3', title: 'Construct Quad Tree', difficulty: 'Medium' },
      { key: 'lc-dc-4', title: 'Merge K Sorted Lists', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Kadane\'s Algorithm',
    icon: '📈',
    color: 'hsl(260, 50%, 55%)',
    problems: [
      { key: 'lc-ka-1', title: 'Maximum Subarray', difficulty: 'Medium' },
      { key: 'lc-ka-2', title: 'Maximum Sum Circular Subarray', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Binary Search',
    icon: '🔍',
    color: 'hsl(270, 60%, 55%)',
    problems: [
      { key: 'lc-bs-1', title: 'Search Insert Position', difficulty: 'Easy' },
      { key: 'lc-bs-2', title: 'Search in Rotated Sorted Array', difficulty: 'Medium' },
      { key: 'lc-bs-3', title: 'Find First and Last Position of Element', difficulty: 'Medium' },
      { key: 'lc-bs-4', title: 'Find Peak Element', difficulty: 'Medium' },
      { key: 'lc-bs-5', title: 'Search a 2D Matrix', difficulty: 'Medium' },
      { key: 'lc-bs-6', title: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium' },
      { key: 'lc-bs-7', title: 'Median of Two Sorted Arrays', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Heap',
    icon: '⛰️',
    color: 'hsl(0, 60%, 55%)',
    problems: [
      { key: 'lc-hp-1', title: 'Kth Largest Element in an Array', difficulty: 'Medium' },
      { key: 'lc-hp-2', title: 'IPO', difficulty: 'Hard' },
      { key: 'lc-hp-3', title: 'Find K Pairs with Smallest Sums', difficulty: 'Medium' },
      { key: 'lc-hp-4', title: 'Find Median from Data Stream', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Bit Manipulation',
    icon: '⚡',
    color: 'hsl(60, 70%, 45%)',
    problems: [
      { key: 'lc-bm-1', title: 'Add Binary', difficulty: 'Easy' },
      { key: 'lc-bm-2', title: 'Reverse Bits', difficulty: 'Easy' },
      { key: 'lc-bm-3', title: 'Number of 1 Bits', difficulty: 'Easy' },
      { key: 'lc-bm-4', title: 'Single Number', difficulty: 'Easy' },
      { key: 'lc-bm-5', title: 'Single Number II', difficulty: 'Medium' },
      { key: 'lc-bm-6', title: 'Bitwise AND of Numbers Range', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Math',
    icon: '🧮',
    color: 'hsl(45, 80%, 50%)',
    problems: [
      { key: 'lc-mt-1', title: 'Palindrome Number', difficulty: 'Easy' },
      { key: 'lc-mt-2', title: 'Plus One', difficulty: 'Easy' },
      { key: 'lc-mt-3', title: 'Factorial Trailing Zeroes', difficulty: 'Medium' },
      { key: 'lc-mt-4', title: 'Sqrt(x)', difficulty: 'Easy' },
      { key: 'lc-mt-5', title: 'Pow(x, n)', difficulty: 'Medium' },
      { key: 'lc-mt-6', title: 'Max Points on a Line', difficulty: 'Hard' },
    ],
  },
  {
    name: '1D Dynamic Programming',
    icon: '📈',
    color: 'hsl(260, 60%, 55%)',
    problems: [
      { key: 'lc-1dp-1', title: 'Climbing Stairs', difficulty: 'Easy' },
      { key: 'lc-1dp-2', title: 'House Robber', difficulty: 'Medium' },
      { key: 'lc-1dp-3', title: 'Word Break', difficulty: 'Medium' },
      { key: 'lc-1dp-4', title: 'Coin Change', difficulty: 'Medium' },
      { key: 'lc-1dp-5', title: 'Longest Increasing Subsequence', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Multidimensional DP',
    icon: '📐',
    color: 'hsl(300, 50%, 50%)',
    problems: [
      { key: 'lc-mdp-1', title: 'Triangle', difficulty: 'Medium' },
      { key: 'lc-mdp-2', title: 'Minimum Path Sum', difficulty: 'Medium' },
      { key: 'lc-mdp-3', title: 'Unique Paths II', difficulty: 'Medium' },
      { key: 'lc-mdp-4', title: 'Longest Palindromic Substring', difficulty: 'Medium' },
      { key: 'lc-mdp-5', title: 'Interleaving String', difficulty: 'Medium' },
      { key: 'lc-mdp-6', title: 'Edit Distance', difficulty: 'Medium' },
      { key: 'lc-mdp-7', title: 'Best Time to Buy and Sell Stock III', difficulty: 'Hard' },
      { key: 'lc-mdp-8', title: 'Best Time to Buy and Sell Stock IV', difficulty: 'Hard' },
      { key: 'lc-mdp-9', title: 'Maximal Square', difficulty: 'Medium' },
    ],
  },
];

// Sort problems within each topic: Easy → Medium → Hard
const difficultyOrder: Record<string, number> = { Easy: 0, Medium: 1, Hard: 2 };
LEETCODE_TOP150_ROADMAP.forEach(topic => {
  topic.problems.sort((a, b) => (difficultyOrder[a.difficulty] ?? 1) - (difficultyOrder[b.difficulty] ?? 1));
});

export const getLeetcodeTop150TotalProblems = () =>
  LEETCODE_TOP150_ROADMAP.reduce((sum, t) => sum + t.problems.length, 0);
