import { type RoadmapProblem, type RoadmapTopic } from './striver-roadmap-data';

export const NEETCODE_ROADMAP: RoadmapTopic[] = [
  {
    name: 'Arrays & Hashing',
    icon: '📊',
    color: 'hsl(220, 70%, 55%)',
    problems: [
      { key: 'nc-ah-1', title: 'Contains Duplicate', difficulty: 'Easy' },
      { key: 'nc-ah-2', title: 'Valid Anagram', difficulty: 'Easy' },
      { key: 'nc-ah-3', title: 'Two Sum', difficulty: 'Easy' },
      { key: 'nc-ah-4', title: 'Group Anagrams', difficulty: 'Medium' },
      { key: 'nc-ah-5', title: 'Top K Frequent Elements', difficulty: 'Medium' },
      { key: 'nc-ah-6', title: 'Encode and Decode Strings', difficulty: 'Medium' },
      { key: 'nc-ah-7', title: 'Product of Array Except Self', difficulty: 'Medium' },
      { key: 'nc-ah-8', title: 'Valid Sudoku', difficulty: 'Medium' },
      { key: 'nc-ah-9', title: 'Longest Consecutive Sequence', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Two Pointers',
    icon: '👆',
    color: 'hsl(180, 60%, 45%)',
    problems: [
      { key: 'nc-tp-1', title: 'Valid Palindrome', difficulty: 'Easy' },
      { key: 'nc-tp-2', title: 'Two Sum II - Input Array Is Sorted', difficulty: 'Medium' },
      { key: 'nc-tp-3', title: '3Sum', difficulty: 'Medium' },
      { key: 'nc-tp-4', title: 'Container With Most Water', difficulty: 'Medium' },
      { key: 'nc-tp-5', title: 'Trapping Rain Water', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Sliding Window',
    icon: '🪟',
    color: 'hsl(200, 70%, 50%)',
    problems: [
      { key: 'nc-sw-1', title: 'Best Time to Buy and Sell Stock', difficulty: 'Easy' },
      { key: 'nc-sw-2', title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium' },
      { key: 'nc-sw-3', title: 'Longest Repeating Character Replacement', difficulty: 'Medium' },
      { key: 'nc-sw-4', title: 'Permutation in String', difficulty: 'Medium' },
      { key: 'nc-sw-5', title: 'Minimum Window Substring', difficulty: 'Hard' },
      { key: 'nc-sw-6', title: 'Sliding Window Maximum', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Stack',
    icon: '📚',
    color: 'hsl(30, 80%, 55%)',
    problems: [
      { key: 'nc-st-1', title: 'Valid Parentheses', difficulty: 'Easy' },
      { key: 'nc-st-2', title: 'Min Stack', difficulty: 'Medium' },
      { key: 'nc-st-3', title: 'Evaluate Reverse Polish Notation', difficulty: 'Medium' },
      { key: 'nc-st-4', title: 'Generate Parentheses', difficulty: 'Medium' },
      { key: 'nc-st-5', title: 'Daily Temperatures', difficulty: 'Medium' },
      { key: 'nc-st-6', title: 'Car Fleet', difficulty: 'Medium' },
      { key: 'nc-st-7', title: 'Largest Rectangle in Histogram', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Binary Search',
    icon: '🔍',
    color: 'hsl(270, 60%, 55%)',
    problems: [
      { key: 'nc-bs-1', title: 'Binary Search', difficulty: 'Easy' },
      { key: 'nc-bs-2', title: 'Search a 2D Matrix', difficulty: 'Medium' },
      { key: 'nc-bs-3', title: 'Koko Eating Bananas', difficulty: 'Medium' },
      { key: 'nc-bs-4', title: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium' },
      { key: 'nc-bs-5', title: 'Search in Rotated Sorted Array', difficulty: 'Medium' },
      { key: 'nc-bs-6', title: 'Time Based Key-Value Store', difficulty: 'Medium' },
      { key: 'nc-bs-7', title: 'Median of Two Sorted Arrays', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Linked List',
    icon: '🔗',
    color: 'hsl(150, 70%, 45%)',
    problems: [
      { key: 'nc-ll-1', title: 'Reverse Linked List', difficulty: 'Easy' },
      { key: 'nc-ll-2', title: 'Merge Two Sorted Lists', difficulty: 'Easy' },
      { key: 'nc-ll-3', title: 'Linked List Cycle', difficulty: 'Easy' },
      { key: 'nc-ll-4', title: 'Reorder List', difficulty: 'Medium' },
      { key: 'nc-ll-5', title: 'Remove Nth Node From End of List', difficulty: 'Medium' },
      { key: 'nc-ll-6', title: 'Copy List with Random Pointer', difficulty: 'Medium' },
      { key: 'nc-ll-7', title: 'Add Two Numbers', difficulty: 'Medium' },
      { key: 'nc-ll-8', title: 'Find the Duplicate Number', difficulty: 'Medium' },
      { key: 'nc-ll-9', title: 'LRU Cache', difficulty: 'Medium' },
      { key: 'nc-ll-10', title: 'Merge K Sorted Lists', difficulty: 'Hard' },
      { key: 'nc-ll-11', title: 'Reverse Nodes in K-Group', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Trees',
    icon: '🌳',
    color: 'hsl(120, 50%, 45%)',
    problems: [
      { key: 'nc-tr-1', title: 'Invert Binary Tree', difficulty: 'Easy' },
      { key: 'nc-tr-2', title: 'Maximum Depth of Binary Tree', difficulty: 'Easy' },
      { key: 'nc-tr-3', title: 'Diameter of Binary Tree', difficulty: 'Easy' },
      { key: 'nc-tr-4', title: 'Balanced Binary Tree', difficulty: 'Easy' },
      { key: 'nc-tr-5', title: 'Same Tree', difficulty: 'Easy' },
      { key: 'nc-tr-6', title: 'Subtree of Another Tree', difficulty: 'Easy' },
      { key: 'nc-tr-7', title: 'Lowest Common Ancestor of BST', difficulty: 'Medium' },
      { key: 'nc-tr-8', title: 'Binary Tree Level Order Traversal', difficulty: 'Medium' },
      { key: 'nc-tr-9', title: 'Binary Tree Right Side View', difficulty: 'Medium' },
      { key: 'nc-tr-10', title: 'Count Good Nodes in Binary Tree', difficulty: 'Medium' },
      { key: 'nc-tr-11', title: 'Validate Binary Search Tree', difficulty: 'Medium' },
      { key: 'nc-tr-12', title: 'Kth Smallest Element in a BST', difficulty: 'Medium' },
      { key: 'nc-tr-13', title: 'Construct Binary Tree from Preorder and Inorder', difficulty: 'Medium' },
      { key: 'nc-tr-14', title: 'Binary Tree Maximum Path Sum', difficulty: 'Hard' },
      { key: 'nc-tr-15', title: 'Serialize and Deserialize Binary Tree', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Tries',
    icon: '🔤',
    color: 'hsl(290, 60%, 55%)',
    problems: [
      { key: 'nc-ti-1', title: 'Implement Trie (Prefix Tree)', difficulty: 'Medium' },
      { key: 'nc-ti-2', title: 'Design Add and Search Words Data Structure', difficulty: 'Medium' },
      { key: 'nc-ti-3', title: 'Word Search II', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Heap / Priority Queue',
    icon: '⛰️',
    color: 'hsl(0, 60%, 55%)',
    problems: [
      { key: 'nc-hp-1', title: 'Kth Largest Element in a Stream', difficulty: 'Easy' },
      { key: 'nc-hp-2', title: 'Last Stone Weight', difficulty: 'Easy' },
      { key: 'nc-hp-3', title: 'K Closest Points to Origin', difficulty: 'Medium' },
      { key: 'nc-hp-4', title: 'Kth Largest Element in an Array', difficulty: 'Medium' },
      { key: 'nc-hp-5', title: 'Task Scheduler', difficulty: 'Medium' },
      { key: 'nc-hp-6', title: 'Design Twitter', difficulty: 'Medium' },
      { key: 'nc-hp-7', title: 'Find Median from Data Stream', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Backtracking',
    icon: '🔄',
    color: 'hsl(340, 70%, 55%)',
    problems: [
      { key: 'nc-bt-1', title: 'Subsets', difficulty: 'Medium' },
      { key: 'nc-bt-2', title: 'Combination Sum', difficulty: 'Medium' },
      { key: 'nc-bt-3', title: 'Permutations', difficulty: 'Medium' },
      { key: 'nc-bt-4', title: 'Subsets II', difficulty: 'Medium' },
      { key: 'nc-bt-5', title: 'Combination Sum II', difficulty: 'Medium' },
      { key: 'nc-bt-6', title: 'Word Search', difficulty: 'Medium' },
      { key: 'nc-bt-7', title: 'Palindrome Partitioning', difficulty: 'Medium' },
      { key: 'nc-bt-8', title: 'Letter Combinations of a Phone Number', difficulty: 'Medium' },
      { key: 'nc-bt-9', title: 'N-Queens', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Graphs',
    icon: '🕸️',
    color: 'hsl(160, 60%, 45%)',
    problems: [
      { key: 'nc-gr-1', title: 'Number of Islands', difficulty: 'Medium' },
      { key: 'nc-gr-2', title: 'Clone Graph', difficulty: 'Medium' },
      { key: 'nc-gr-3', title: 'Max Area of Island', difficulty: 'Medium' },
      { key: 'nc-gr-4', title: 'Pacific Atlantic Water Flow', difficulty: 'Medium' },
      { key: 'nc-gr-5', title: 'Surrounded Regions', difficulty: 'Medium' },
      { key: 'nc-gr-6', title: 'Rotting Oranges', difficulty: 'Medium' },
      { key: 'nc-gr-7', title: 'Walls and Gates', difficulty: 'Medium' },
      { key: 'nc-gr-8', title: 'Course Schedule', difficulty: 'Medium' },
      { key: 'nc-gr-9', title: 'Course Schedule II', difficulty: 'Medium' },
      { key: 'nc-gr-10', title: 'Redundant Connection', difficulty: 'Medium' },
      { key: 'nc-gr-11', title: 'Number of Connected Components in Graph', difficulty: 'Medium' },
      { key: 'nc-gr-12', title: 'Graph Valid Tree', difficulty: 'Medium' },
      { key: 'nc-gr-13', title: 'Word Ladder', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Advanced Graphs',
    icon: '🗺️',
    color: 'hsl(45, 80%, 50%)',
    problems: [
      { key: 'nc-ag-1', title: 'Reconstruct Itinerary', difficulty: 'Hard' },
      { key: 'nc-ag-2', title: 'Min Cost to Connect All Points', difficulty: 'Medium' },
      { key: 'nc-ag-3', title: 'Network Delay Time', difficulty: 'Medium' },
      { key: 'nc-ag-4', title: 'Swim in Rising Water', difficulty: 'Hard' },
      { key: 'nc-ag-5', title: 'Alien Dictionary', difficulty: 'Hard' },
      { key: 'nc-ag-6', title: 'Cheapest Flights Within K Stops', difficulty: 'Medium' },
    ],
  },
  {
    name: '1-D Dynamic Programming',
    icon: '📈',
    color: 'hsl(260, 60%, 55%)',
    problems: [
      { key: 'nc-dp1-1', title: 'Climbing Stairs', difficulty: 'Easy' },
      { key: 'nc-dp1-2', title: 'Min Cost Climbing Stairs', difficulty: 'Easy' },
      { key: 'nc-dp1-3', title: 'House Robber', difficulty: 'Medium' },
      { key: 'nc-dp1-4', title: 'House Robber II', difficulty: 'Medium' },
      { key: 'nc-dp1-5', title: 'Longest Palindromic Substring', difficulty: 'Medium' },
      { key: 'nc-dp1-6', title: 'Palindromic Substrings', difficulty: 'Medium' },
      { key: 'nc-dp1-7', title: 'Decode Ways', difficulty: 'Medium' },
      { key: 'nc-dp1-8', title: 'Coin Change', difficulty: 'Medium' },
      { key: 'nc-dp1-9', title: 'Maximum Product Subarray', difficulty: 'Medium' },
      { key: 'nc-dp1-10', title: 'Word Break', difficulty: 'Medium' },
      { key: 'nc-dp1-11', title: 'Longest Increasing Subsequence', difficulty: 'Medium' },
      { key: 'nc-dp1-12', title: 'Partition Equal Subset Sum', difficulty: 'Medium' },
    ],
  },
  {
    name: '2-D Dynamic Programming',
    icon: '📐',
    color: 'hsl(300, 50%, 50%)',
    problems: [
      { key: 'nc-dp2-1', title: 'Unique Paths', difficulty: 'Medium' },
      { key: 'nc-dp2-2', title: 'Longest Common Subsequence', difficulty: 'Medium' },
      { key: 'nc-dp2-3', title: 'Best Time to Buy and Sell Stock with Cooldown', difficulty: 'Medium' },
      { key: 'nc-dp2-4', title: 'Coin Change II', difficulty: 'Medium' },
      { key: 'nc-dp2-5', title: 'Target Sum', difficulty: 'Medium' },
      { key: 'nc-dp2-6', title: 'Interleaving String', difficulty: 'Medium' },
      { key: 'nc-dp2-7', title: 'Longest Increasing Path in a Matrix', difficulty: 'Hard' },
      { key: 'nc-dp2-8', title: 'Distinct Subsequences', difficulty: 'Hard' },
      { key: 'nc-dp2-9', title: 'Edit Distance', difficulty: 'Medium' },
      { key: 'nc-dp2-10', title: 'Burst Balloons', difficulty: 'Hard' },
      { key: 'nc-dp2-11', title: 'Regular Expression Matching', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Greedy',
    icon: '💰',
    color: 'hsl(50, 80%, 50%)',
    problems: [
      { key: 'nc-gd-1', title: 'Maximum Subarray', difficulty: 'Medium' },
      { key: 'nc-gd-2', title: 'Jump Game', difficulty: 'Medium' },
      { key: 'nc-gd-3', title: 'Jump Game II', difficulty: 'Medium' },
      { key: 'nc-gd-4', title: 'Gas Station', difficulty: 'Medium' },
      { key: 'nc-gd-5', title: 'Hand of Straights', difficulty: 'Medium' },
      { key: 'nc-gd-6', title: 'Merge Triplets to Form Target Triplet', difficulty: 'Medium' },
      { key: 'nc-gd-7', title: 'Partition Labels', difficulty: 'Medium' },
      { key: 'nc-gd-8', title: 'Valid Parenthesis String', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Intervals',
    icon: '📏',
    color: 'hsl(15, 70%, 55%)',
    problems: [
      { key: 'nc-iv-1', title: 'Insert Interval', difficulty: 'Medium' },
      { key: 'nc-iv-2', title: 'Merge Intervals', difficulty: 'Medium' },
      { key: 'nc-iv-3', title: 'Non-Overlapping Intervals', difficulty: 'Medium' },
      { key: 'nc-iv-4', title: 'Meeting Rooms', difficulty: 'Easy' },
      { key: 'nc-iv-5', title: 'Meeting Rooms II', difficulty: 'Medium' },
      { key: 'nc-iv-6', title: 'Minimum Interval to Include Each Query', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Math & Geometry',
    icon: '🔢',
    color: 'hsl(90, 50%, 50%)',
    problems: [
      { key: 'nc-mg-1', title: 'Rotate Image', difficulty: 'Medium' },
      { key: 'nc-mg-2', title: 'Spiral Matrix', difficulty: 'Medium' },
      { key: 'nc-mg-3', title: 'Set Matrix Zeroes', difficulty: 'Medium' },
      { key: 'nc-mg-4', title: 'Happy Number', difficulty: 'Easy' },
      { key: 'nc-mg-5', title: 'Plus One', difficulty: 'Easy' },
      { key: 'nc-mg-6', title: 'Pow(x, n)', difficulty: 'Medium' },
      { key: 'nc-mg-7', title: 'Multiply Strings', difficulty: 'Medium' },
      { key: 'nc-mg-8', title: 'Detect Squares', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Bit Manipulation',
    icon: '⚡',
    color: 'hsl(60, 70%, 45%)',
    problems: [
      { key: 'nc-bm-1', title: 'Single Number', difficulty: 'Easy' },
      { key: 'nc-bm-2', title: 'Number of 1 Bits', difficulty: 'Easy' },
      { key: 'nc-bm-3', title: 'Counting Bits', difficulty: 'Easy' },
      { key: 'nc-bm-4', title: 'Reverse Bits', difficulty: 'Easy' },
      { key: 'nc-bm-5', title: 'Missing Number', difficulty: 'Easy' },
      { key: 'nc-bm-6', title: 'Sum of Two Integers', difficulty: 'Medium' },
      { key: 'nc-bm-7', title: 'Reverse Integer', difficulty: 'Medium' },
    ],
  },
];

// Sort problems within each topic: Easy → Medium → Hard
const difficultyOrder: Record<string, number> = { Easy: 0, Medium: 1, Hard: 2 };
NEETCODE_ROADMAP.forEach(topic => {
  topic.problems.sort((a, b) => (difficultyOrder[a.difficulty] ?? 1) - (difficultyOrder[b.difficulty] ?? 1));
});

export const getNeetcodeTotalProblems = () =>
  NEETCODE_ROADMAP.reduce((sum, t) => sum + t.problems.length, 0);
