export interface RoadmapProblem {
  key: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  link?: string;
  starterCode?: string;
  description?: string;
}

export interface RoadmapTopic {
  name: string;
  icon: string;
  color: string;
  problems: RoadmapProblem[];
}

export const STRIVER_ROADMAP: RoadmapTopic[] = [
  {
    name: 'Arrays',
    icon: '📊',
    color: 'hsl(var(--primary))',
    problems: [
      { key: 'arr-1', title: 'Set Matrix Zeroes', difficulty: 'Medium' },
      { key: 'arr-2', title: 'Pascal\'s Triangle', difficulty: 'Easy' },
      { key: 'arr-3', title: 'Next Permutation', difficulty: 'Medium' },
      { key: 'arr-4', title: 'Kadane\'s Algorithm (Max Subarray Sum)', difficulty: 'Medium' },
      { key: 'arr-5', title: 'Sort an Array of 0s, 1s and 2s', difficulty: 'Medium' },
      { key: 'arr-6', title: 'Stock Buy and Sell', difficulty: 'Easy' },
      { key: 'arr-7', title: 'Rotate Matrix by 90 Degrees', difficulty: 'Medium' },
      { key: 'arr-8', title: 'Merge Overlapping Intervals', difficulty: 'Medium' },
      { key: 'arr-9', title: 'Merge Two Sorted Arrays Without Extra Space', difficulty: 'Hard' },
      { key: 'arr-10', title: 'Find the Duplicate Number', difficulty: 'Medium' },
      { key: 'arr-11', title: 'Repeat and Missing Number', difficulty: 'Medium' },
      { key: 'arr-12', title: 'Inversion of Array (Merge Sort)', difficulty: 'Hard' },
      { key: 'arr-13', title: 'Search in a 2D Matrix', difficulty: 'Medium' },
      { key: 'arr-14', title: 'Pow(x, n)', difficulty: 'Medium' },
      { key: 'arr-15', title: 'Majority Element (>N/2)', difficulty: 'Easy' },
      { key: 'arr-16', title: 'Majority Element (>N/3)', difficulty: 'Medium' },
      { key: 'arr-17', title: 'Grid Unique Paths', difficulty: 'Medium' },
      { key: 'arr-18', title: 'Reverse Pairs', difficulty: 'Hard' },
      { key: 'arr-19', title: '2 Sum Problem', difficulty: 'Easy' },
      { key: 'arr-20', title: '4 Sum Problem', difficulty: 'Medium' },
      { key: 'arr-21', title: 'Longest Consecutive Sequence', difficulty: 'Medium' },
      { key: 'arr-22', title: 'Largest Subarray with K Sum', difficulty: 'Medium' },
      { key: 'arr-23', title: 'Count Subarrays with Given XOR', difficulty: 'Medium' },
      { key: 'arr-24', title: 'Longest Substring Without Repeating', difficulty: 'Medium' },
      { key: 'arr-25', title: '3 Sum Problem', difficulty: 'Medium' },
      { key: 'arr-26', title: 'Trapping Rain Water', difficulty: 'Hard' },
      { key: 'arr-27', title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy' },
      { key: 'arr-28', title: 'Max Consecutive Ones', difficulty: 'Easy' },
      { key: 'arr-29', title: 'Find the Number that Appears Once', difficulty: 'Easy' },
      { key: 'arr-30', title: 'Longest Subarray with Sum K (Positives)', difficulty: 'Easy' },
    ],
  },
  {
    name: 'Strings',
    icon: '📝',
    color: 'hsl(210, 80%, 60%)',
    problems: [
      { key: 'str-1', title: 'Reverse Words in a String', difficulty: 'Medium' },
      { key: 'str-2', title: 'Longest Palindromic Substring', difficulty: 'Medium' },
      { key: 'str-3', title: 'Roman to Integer', difficulty: 'Easy' },
      { key: 'str-4', title: 'String to Integer (atoi)', difficulty: 'Medium' },
      { key: 'str-5', title: 'Longest Common Prefix', difficulty: 'Easy' },
      { key: 'str-6', title: 'Rabin-Karp Algorithm', difficulty: 'Hard' },
      { key: 'str-7', title: 'Z-Algorithm', difficulty: 'Hard' },
      { key: 'str-8', title: 'KMP Algorithm', difficulty: 'Hard' },
      { key: 'str-9', title: 'Minimum Characters for Palindrome', difficulty: 'Hard' },
      { key: 'str-10', title: 'Valid Anagram', difficulty: 'Easy' },
      { key: 'str-11', title: 'Count and Say', difficulty: 'Medium' },
      { key: 'str-12', title: 'Compare Version Numbers', difficulty: 'Medium' },
      { key: 'str-13', title: 'Encode and Decode Strings', difficulty: 'Medium' },
      { key: 'str-14', title: 'Isomorphic Strings', difficulty: 'Easy' },
      { key: 'str-15', title: 'Check if Two Strings are Anagrams', difficulty: 'Easy' },
      { key: 'str-16', title: 'Sort Characters by Frequency', difficulty: 'Medium' },
      { key: 'str-17', title: 'Maximum Nesting Depth of Parentheses', difficulty: 'Easy' },
      { key: 'str-18', title: 'Remove Outermost Parentheses', difficulty: 'Easy' },
      { key: 'str-19', title: 'Largest Odd Number in String', difficulty: 'Easy' },
      { key: 'str-20', title: 'Rotate String', difficulty: 'Easy' },
      { key: 'str-21', title: 'Beautiful Arrangement of Strings', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Linked List',
    icon: '🔗',
    color: 'hsl(150, 70%, 45%)',
    problems: [
      { key: 'll-1', title: 'Reverse a Linked List', difficulty: 'Easy' },
      { key: 'll-2', title: 'Middle of Linked List', difficulty: 'Easy' },
      { key: 'll-3', title: 'Merge Two Sorted Lists', difficulty: 'Easy' },
      { key: 'll-4', title: 'Remove Nth Node from End', difficulty: 'Medium' },
      { key: 'll-5', title: 'Add Two Numbers as Linked List', difficulty: 'Medium' },
      { key: 'll-6', title: 'Delete Node in a Linked List', difficulty: 'Easy' },
      { key: 'll-7', title: 'Intersection of Two Linked Lists', difficulty: 'Easy' },
      { key: 'll-8', title: 'Detect Cycle in Linked List', difficulty: 'Easy' },
      { key: 'll-9', title: 'Find Starting Point of Loop', difficulty: 'Medium' },
      { key: 'll-10', title: 'Palindrome Linked List', difficulty: 'Medium' },
      { key: 'll-11', title: 'Reverse Linked List in Groups of K', difficulty: 'Hard' },
      { key: 'll-12', title: 'Rotate a Linked List', difficulty: 'Medium' },
      { key: 'll-13', title: 'Flattening a Linked List', difficulty: 'Medium' },
      { key: 'll-14', title: 'Clone a Linked List with Random Pointer', difficulty: 'Medium' },
      { key: 'll-15', title: 'Sort Linked List (Merge Sort)', difficulty: 'Medium' },
      { key: 'll-16', title: 'Find Length of Loop', difficulty: 'Medium' },
      { key: 'll-17', title: 'Odd Even Linked List', difficulty: 'Medium' },
      { key: 'll-18', title: 'Delete Middle Node', difficulty: 'Medium' },
      { key: 'll-19', title: 'Segregate Even and Odd Nodes', difficulty: 'Medium' },
      { key: 'll-20', title: 'Remove Duplicates from Sorted List', difficulty: 'Easy' },
    ],
  },
  {
    name: 'Stack & Queue',
    icon: '📚',
    color: 'hsl(30, 80%, 55%)',
    problems: [
      { key: 'sq-1', title: 'Implement Stack Using Arrays', difficulty: 'Easy' },
      { key: 'sq-2', title: 'Implement Queue Using Arrays', difficulty: 'Easy' },
      { key: 'sq-3', title: 'Implement Stack Using Queue', difficulty: 'Medium' },
      { key: 'sq-4', title: 'Implement Queue Using Stack', difficulty: 'Medium' },
      { key: 'sq-5', title: 'Valid Parentheses', difficulty: 'Easy' },
      { key: 'sq-6', title: 'Min Stack', difficulty: 'Medium' },
      { key: 'sq-7', title: 'Infix to Postfix', difficulty: 'Medium' },
      { key: 'sq-8', title: 'Prefix to Infix', difficulty: 'Medium' },
      { key: 'sq-9', title: 'Next Greater Element', difficulty: 'Medium' },
      { key: 'sq-10', title: 'Next Smaller Element', difficulty: 'Medium' },
      { key: 'sq-11', title: 'Nearest Smaller to Left', difficulty: 'Medium' },
      { key: 'sq-12', title: 'Largest Rectangle in Histogram', difficulty: 'Hard' },
      { key: 'sq-13', title: 'Sliding Window Maximum', difficulty: 'Hard' },
      { key: 'sq-14', title: 'Implement LRU Cache', difficulty: 'Hard' },
      { key: 'sq-15', title: 'Implement LFU Cache', difficulty: 'Hard' },
      { key: 'sq-16', title: 'Celebrity Problem', difficulty: 'Medium' },
      { key: 'sq-17', title: 'Online Stock Span', difficulty: 'Medium' },
      { key: 'sq-18', title: 'Maximum of Minimum for Every Window Size', difficulty: 'Hard' },
      { key: 'sq-19', title: 'Rotten Oranges (BFS)', difficulty: 'Medium' },
      { key: 'sq-20', title: 'Daily Temperatures', difficulty: 'Medium' },
      { key: 'sq-21', title: 'Asteroid Collision', difficulty: 'Medium' },
      { key: 'sq-22', title: 'Sum of Subarray Minimums', difficulty: 'Medium' },
      { key: 'sq-23', title: 'Trapping Rain Water', difficulty: 'Hard' },
      { key: 'sq-24', title: 'Stock Span Problem', difficulty: 'Medium' },
      { key: 'sq-25', title: 'Remove K Digits', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Binary Search',
    icon: '🔍',
    color: 'hsl(270, 60%, 55%)',
    problems: [
      { key: 'bs-1', title: 'Binary Search', difficulty: 'Easy' },
      { key: 'bs-2', title: 'Lower Bound and Upper Bound', difficulty: 'Easy' },
      { key: 'bs-3', title: 'Search Insert Position', difficulty: 'Easy' },
      { key: 'bs-4', title: 'Floor and Ceil in Sorted Array', difficulty: 'Easy' },
      { key: 'bs-5', title: 'First and Last Occurrence', difficulty: 'Medium' },
      { key: 'bs-6', title: 'Count Occurrences in Sorted Array', difficulty: 'Easy' },
      { key: 'bs-7', title: 'Search in Rotated Sorted Array', difficulty: 'Medium' },
      { key: 'bs-8', title: 'Search in Rotated Sorted Array II', difficulty: 'Medium' },
      { key: 'bs-9', title: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium' },
      { key: 'bs-10', title: 'Single Element in a Sorted Array', difficulty: 'Medium' },
      { key: 'bs-11', title: 'Find Peak Element', difficulty: 'Medium' },
      { key: 'bs-12', title: 'Nth Root of M', difficulty: 'Medium' },
      { key: 'bs-13', title: 'Koko Eating Bananas', difficulty: 'Medium' },
      { key: 'bs-14', title: 'Minimum Days to Make Bouquets', difficulty: 'Medium' },
      { key: 'bs-15', title: 'Find the Smallest Divisor', difficulty: 'Medium' },
      { key: 'bs-16', title: 'Capacity to Ship Packages', difficulty: 'Medium' },
      { key: 'bs-17', title: 'Aggressive Cows', difficulty: 'Hard' },
      { key: 'bs-18', title: 'Book Allocation Problem', difficulty: 'Hard' },
      { key: 'bs-19', title: 'Split Array Largest Sum', difficulty: 'Hard' },
      { key: 'bs-20', title: 'Painter\'s Partition Problem', difficulty: 'Hard' },
      { key: 'bs-21', title: 'Median of Two Sorted Arrays', difficulty: 'Hard' },
      { key: 'bs-22', title: 'Kth Element of Two Sorted Arrays', difficulty: 'Medium' },
      { key: 'bs-23', title: 'Row with Maximum 1s', difficulty: 'Easy' },
      { key: 'bs-24', title: 'Search in 2D Matrix', difficulty: 'Medium' },
      { key: 'bs-25', title: 'Search in 2D Matrix II', difficulty: 'Medium' },
      { key: 'bs-26', title: 'Find Peak Element in 2D Grid', difficulty: 'Hard' },
      { key: 'bs-27', title: 'Median in Row-Wise Sorted Matrix', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Recursion & Backtracking',
    icon: '🔄',
    color: 'hsl(340, 70%, 55%)',
    problems: [
      { key: 'rec-1', title: 'Print All Subsequences', difficulty: 'Easy' },
      { key: 'rec-2', title: 'Print All Permutations', difficulty: 'Medium' },
      { key: 'rec-3', title: 'Combination Sum I', difficulty: 'Medium' },
      { key: 'rec-4', title: 'Combination Sum II', difficulty: 'Medium' },
      { key: 'rec-5', title: 'Subset Sum I', difficulty: 'Medium' },
      { key: 'rec-6', title: 'Subset Sum II', difficulty: 'Medium' },
      { key: 'rec-7', title: 'N-Queens Problem', difficulty: 'Hard' },
      { key: 'rec-8', title: 'Sudoku Solver', difficulty: 'Hard' },
      { key: 'rec-9', title: 'M Coloring Problem', difficulty: 'Medium' },
      { key: 'rec-10', title: 'Rat in a Maze', difficulty: 'Medium' },
      { key: 'rec-11', title: 'Word Break', difficulty: 'Medium' },
      { key: 'rec-12', title: 'Palindrome Partitioning', difficulty: 'Medium' },
      { key: 'rec-13', title: 'K-th Permutation Sequence', difficulty: 'Hard' },
      { key: 'rec-14', title: 'Print All Subsets with Target Sum', difficulty: 'Medium' },
      { key: 'rec-15', title: 'Letter Combinations of Phone Number', difficulty: 'Medium' },
      { key: 'rec-16', title: 'Generate Parentheses', difficulty: 'Medium' },
      { key: 'rec-17', title: 'Power Set', difficulty: 'Medium' },
      { key: 'rec-18', title: 'Word Search', difficulty: 'Medium' },
      { key: 'rec-19', title: 'Expression Add Operators', difficulty: 'Hard' },
      { key: 'rec-20', title: 'Beautiful Arrangement', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Trees',
    icon: '🌳',
    color: 'hsl(120, 50%, 40%)',
    problems: [
      { key: 'tree-1', title: 'Inorder Traversal', difficulty: 'Easy' },
      { key: 'tree-2', title: 'Preorder Traversal', difficulty: 'Easy' },
      { key: 'tree-3', title: 'Postorder Traversal', difficulty: 'Easy' },
      { key: 'tree-4', title: 'Level Order Traversal', difficulty: 'Medium' },
      { key: 'tree-5', title: 'Maximum Depth of Binary Tree', difficulty: 'Easy' },
      { key: 'tree-6', title: 'Check if Balanced Binary Tree', difficulty: 'Easy' },
      { key: 'tree-7', title: 'Diameter of Binary Tree', difficulty: 'Easy' },
      { key: 'tree-8', title: 'Maximum Path Sum', difficulty: 'Hard' },
      { key: 'tree-9', title: 'Same Tree', difficulty: 'Easy' },
      { key: 'tree-10', title: 'Zigzag Level Order Traversal', difficulty: 'Medium' },
      { key: 'tree-11', title: 'Boundary Traversal', difficulty: 'Medium' },
      { key: 'tree-12', title: 'Vertical Order Traversal', difficulty: 'Hard' },
      { key: 'tree-13', title: 'Top View of Binary Tree', difficulty: 'Medium' },
      { key: 'tree-14', title: 'Bottom View of Binary Tree', difficulty: 'Medium' },
      { key: 'tree-15', title: 'Right/Left View of Binary Tree', difficulty: 'Medium' },
      { key: 'tree-16', title: 'Symmetric Binary Tree', difficulty: 'Easy' },
      { key: 'tree-17', title: 'Root to Node Path', difficulty: 'Medium' },
      { key: 'tree-18', title: 'Lowest Common Ancestor', difficulty: 'Medium' },
      { key: 'tree-19', title: 'Maximum Width of Binary Tree', difficulty: 'Medium' },
      { key: 'tree-20', title: 'Check for Children Sum Property', difficulty: 'Medium' },
      { key: 'tree-21', title: 'All Nodes at Distance K', difficulty: 'Medium' },
      { key: 'tree-22', title: 'Burning Tree', difficulty: 'Hard' },
      { key: 'tree-23', title: 'Count Total Nodes in Complete BT', difficulty: 'Medium' },
      { key: 'tree-24', title: 'Serialize and Deserialize BT', difficulty: 'Hard' },
      { key: 'tree-25', title: 'Morris Traversal (Inorder)', difficulty: 'Medium' },
      { key: 'tree-26', title: 'Morris Traversal (Preorder)', difficulty: 'Medium' },
      { key: 'tree-27', title: 'Flatten Binary Tree to Linked List', difficulty: 'Medium' },
      { key: 'tree-28', title: 'Construct BT from Inorder & Preorder', difficulty: 'Medium' },
      { key: 'tree-29', title: 'Construct BT from Inorder & Postorder', difficulty: 'Medium' },
      { key: 'tree-30', title: 'Invert Binary Tree', difficulty: 'Easy' },
    ],
  },
  {
    name: 'Binary Search Trees',
    icon: '🌲',
    color: 'hsl(100, 60%, 40%)',
    problems: [
      { key: 'bst-1', title: 'Search in BST', difficulty: 'Easy' },
      { key: 'bst-2', title: 'Ceil in BST', difficulty: 'Medium' },
      { key: 'bst-3', title: 'Floor in BST', difficulty: 'Medium' },
      { key: 'bst-4', title: 'Insert into BST', difficulty: 'Medium' },
      { key: 'bst-5', title: 'Delete Node in BST', difficulty: 'Medium' },
      { key: 'bst-6', title: 'Kth Smallest Element in BST', difficulty: 'Medium' },
      { key: 'bst-7', title: 'Kth Largest Element in BST', difficulty: 'Medium' },
      { key: 'bst-8', title: 'Validate BST', difficulty: 'Medium' },
      { key: 'bst-9', title: 'LCA in BST', difficulty: 'Medium' },
      { key: 'bst-10', title: 'Construct BST from Preorder', difficulty: 'Medium' },
      { key: 'bst-11', title: 'Inorder Successor in BST', difficulty: 'Medium' },
      { key: 'bst-12', title: 'BST Iterator', difficulty: 'Medium' },
      { key: 'bst-13', title: 'Two Sum in BST', difficulty: 'Easy' },
      { key: 'bst-14', title: 'Recover BST (Swap Two Nodes)', difficulty: 'Medium' },
      { key: 'bst-15', title: 'Largest BST in Binary Tree', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Heaps',
    icon: '⛰️',
    color: 'hsl(45, 80%, 50%)',
    problems: [
      { key: 'heap-1', title: 'Implement Min Heap', difficulty: 'Medium' },
      { key: 'heap-2', title: 'Implement Max Heap', difficulty: 'Medium' },
      { key: 'heap-3', title: 'Kth Largest Element', difficulty: 'Medium' },
      { key: 'heap-4', title: 'Kth Smallest Element', difficulty: 'Medium' },
      { key: 'heap-5', title: 'Sort K Sorted Array', difficulty: 'Medium' },
      { key: 'heap-6', title: 'Merge K Sorted Lists', difficulty: 'Hard' },
      { key: 'heap-7', title: 'Top K Frequent Elements', difficulty: 'Medium' },
      { key: 'heap-8', title: 'Task Scheduler', difficulty: 'Medium' },
      { key: 'heap-9', title: 'Find Median from Data Stream', difficulty: 'Hard' },
      { key: 'heap-10', title: 'Hand of Straights', difficulty: 'Medium' },
      { key: 'heap-11', title: 'Design Twitter', difficulty: 'Medium' },
      { key: 'heap-12', title: 'K Closest Points to Origin', difficulty: 'Medium' },
      { key: 'heap-13', title: 'Maximum Sum Combinations', difficulty: 'Medium' },
      { key: 'heap-14', title: 'Replace Each Element by Its Rank', difficulty: 'Easy' },
    ],
  },
  {
    name: 'Greedy Algorithms',
    icon: '🎯',
    color: 'hsl(0, 70%, 55%)',
    problems: [
      { key: 'gr-1', title: 'Assign Cookies', difficulty: 'Easy' },
      { key: 'gr-2', title: 'Fractional Knapsack', difficulty: 'Medium' },
      { key: 'gr-3', title: 'Minimum Coins', difficulty: 'Medium' },
      { key: 'gr-4', title: 'Lemonade Change', difficulty: 'Easy' },
      { key: 'gr-5', title: 'Valid Parenthesis String', difficulty: 'Medium' },
      { key: 'gr-6', title: 'N Meetings in One Room', difficulty: 'Easy' },
      { key: 'gr-7', title: 'Jump Game I', difficulty: 'Medium' },
      { key: 'gr-8', title: 'Jump Game II', difficulty: 'Medium' },
      { key: 'gr-9', title: 'Minimum Platforms', difficulty: 'Medium' },
      { key: 'gr-10', title: 'Job Sequencing Problem', difficulty: 'Medium' },
      { key: 'gr-11', title: 'Candy Distribution', difficulty: 'Hard' },
      { key: 'gr-12', title: 'Insert Interval', difficulty: 'Medium' },
      { key: 'gr-13', title: 'Merge Intervals', difficulty: 'Medium' },
      { key: 'gr-14', title: 'Non-Overlapping Intervals', difficulty: 'Medium' },
      { key: 'gr-15', title: 'Gas Station', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Graphs',
    icon: '🕸️',
    color: 'hsl(200, 70%, 50%)',
    problems: [
      { key: 'graph-1', title: 'BFS of Graph', difficulty: 'Easy' },
      { key: 'graph-2', title: 'DFS of Graph', difficulty: 'Easy' },
      { key: 'graph-3', title: 'Number of Provinces', difficulty: 'Medium' },
      { key: 'graph-4', title: 'Number of Islands', difficulty: 'Medium' },
      { key: 'graph-5', title: 'Flood Fill', difficulty: 'Easy' },
      { key: 'graph-6', title: 'Rotten Oranges', difficulty: 'Medium' },
      { key: 'graph-7', title: 'Detect Cycle in Undirected Graph (BFS)', difficulty: 'Medium' },
      { key: 'graph-8', title: 'Detect Cycle in Undirected Graph (DFS)', difficulty: 'Medium' },
      { key: 'graph-9', title: '0/1 Matrix (Nearest Cell with 1)', difficulty: 'Medium' },
      { key: 'graph-10', title: 'Surrounded Regions', difficulty: 'Medium' },
      { key: 'graph-11', title: 'Number of Enclaves', difficulty: 'Medium' },
      { key: 'graph-12', title: 'Word Ladder I', difficulty: 'Hard' },
      { key: 'graph-13', title: 'Word Ladder II', difficulty: 'Hard' },
      { key: 'graph-14', title: 'Number of Distinct Islands', difficulty: 'Medium' },
      { key: 'graph-15', title: 'Bipartite Graph Check (BFS)', difficulty: 'Medium' },
      { key: 'graph-16', title: 'Detect Cycle in Directed Graph (DFS)', difficulty: 'Medium' },
      { key: 'graph-17', title: 'Topological Sort', difficulty: 'Medium' },
      { key: 'graph-18', title: 'Kahn\'s Algorithm (BFS Topo Sort)', difficulty: 'Medium' },
      { key: 'graph-19', title: 'Course Schedule I & II', difficulty: 'Medium' },
      { key: 'graph-20', title: 'Alien Dictionary', difficulty: 'Hard' },
      { key: 'graph-21', title: 'Shortest Path in Undirected Graph', difficulty: 'Medium' },
      { key: 'graph-22', title: 'Shortest Path in DAG', difficulty: 'Medium' },
      { key: 'graph-23', title: 'Dijkstra\'s Algorithm', difficulty: 'Medium' },
      { key: 'graph-24', title: 'Bellman-Ford Algorithm', difficulty: 'Medium' },
      { key: 'graph-25', title: 'Floyd Warshall Algorithm', difficulty: 'Medium' },
      { key: 'graph-26', title: 'City with Smallest Neighbors at Threshold', difficulty: 'Medium' },
      { key: 'graph-27', title: 'Minimum Spanning Tree (Prim\'s)', difficulty: 'Medium' },
      { key: 'graph-28', title: 'Minimum Spanning Tree (Kruskal\'s)', difficulty: 'Medium' },
      { key: 'graph-29', title: 'Number of Operations to Make Network Connected', difficulty: 'Medium' },
      { key: 'graph-30', title: 'Strongly Connected Components (Kosaraju)', difficulty: 'Hard' },
      { key: 'graph-31', title: 'Bridges in Graph (Tarjan\'s)', difficulty: 'Hard' },
      { key: 'graph-32', title: 'Articulation Points', difficulty: 'Hard' },
      { key: 'graph-33', title: 'Cheapest Flights Within K Stops', difficulty: 'Medium' },
      { key: 'graph-34', title: 'Network Delay Time', difficulty: 'Medium' },
      { key: 'graph-35', title: 'Accounts Merge', difficulty: 'Medium' },
      { key: 'graph-36', title: 'Making a Large Island', difficulty: 'Hard' },
      { key: 'graph-37', title: 'Swim in Rising Water', difficulty: 'Hard' },
      { key: 'graph-38', title: 'Clone Graph', difficulty: 'Medium' },
      { key: 'graph-39', title: 'Pacific Atlantic Water Flow', difficulty: 'Medium' },
      { key: 'graph-40', title: 'Redundant Connection', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Dynamic Programming',
    icon: '💡',
    color: 'hsl(50, 90%, 50%)',
    problems: [
      { key: 'dp-1', title: 'Climbing Stairs', difficulty: 'Easy' },
      { key: 'dp-2', title: 'Frog Jump (K Steps)', difficulty: 'Easy' },
      { key: 'dp-3', title: 'House Robber', difficulty: 'Medium' },
      { key: 'dp-4', title: 'House Robber II', difficulty: 'Medium' },
      { key: 'dp-5', title: 'Ninja\'s Training', difficulty: 'Medium' },
      { key: 'dp-6', title: 'Grid Unique Paths', difficulty: 'Medium' },
      { key: 'dp-7', title: 'Grid Unique Paths II (Obstacles)', difficulty: 'Medium' },
      { key: 'dp-8', title: 'Minimum Path Sum', difficulty: 'Medium' },
      { key: 'dp-9', title: 'Triangle Path Sum', difficulty: 'Medium' },
      { key: 'dp-10', title: 'Minimum Falling Path Sum', difficulty: 'Medium' },
      { key: 'dp-11', title: 'Cherry Pickup II', difficulty: 'Hard' },
      { key: 'dp-12', title: 'Subset Sum Problem', difficulty: 'Medium' },
      { key: 'dp-13', title: 'Partition Equal Subset Sum', difficulty: 'Medium' },
      { key: 'dp-14', title: 'Count Subsets with Sum K', difficulty: 'Medium' },
      { key: 'dp-15', title: 'Count Partitions with Given Difference', difficulty: 'Medium' },
      { key: 'dp-16', title: '0/1 Knapsack', difficulty: 'Medium' },
      { key: 'dp-17', title: 'Coin Change I', difficulty: 'Medium' },
      { key: 'dp-18', title: 'Coin Change II', difficulty: 'Medium' },
      { key: 'dp-19', title: 'Target Sum', difficulty: 'Medium' },
      { key: 'dp-20', title: 'Unbounded Knapsack', difficulty: 'Medium' },
      { key: 'dp-21', title: 'Rod Cutting', difficulty: 'Medium' },
      { key: 'dp-22', title: 'Longest Common Subsequence', difficulty: 'Medium' },
      { key: 'dp-23', title: 'Print LCS', difficulty: 'Medium' },
      { key: 'dp-24', title: 'Longest Common Substring', difficulty: 'Medium' },
      { key: 'dp-25', title: 'Shortest Common Supersequence', difficulty: 'Hard' },
      { key: 'dp-26', title: 'Distinct Subsequences', difficulty: 'Hard' },
      { key: 'dp-27', title: 'Edit Distance', difficulty: 'Medium' },
      { key: 'dp-28', title: 'Wildcard Matching', difficulty: 'Hard' },
      { key: 'dp-29', title: 'Longest Increasing Subsequence', difficulty: 'Medium' },
      { key: 'dp-30', title: 'Print LIS', difficulty: 'Medium' },
      { key: 'dp-31', title: 'Longest Bitonic Subsequence', difficulty: 'Medium' },
      { key: 'dp-32', title: 'Number of LIS', difficulty: 'Medium' },
      { key: 'dp-33', title: 'Largest Divisible Subset', difficulty: 'Medium' },
      { key: 'dp-34', title: 'Longest String Chain', difficulty: 'Medium' },
      { key: 'dp-35', title: 'Matrix Chain Multiplication', difficulty: 'Hard' },
      { key: 'dp-36', title: 'Minimum Cost to Cut a Stick', difficulty: 'Hard' },
      { key: 'dp-37', title: 'Burst Balloons', difficulty: 'Hard' },
      { key: 'dp-38', title: 'Evaluate Boolean Expression', difficulty: 'Hard' },
      { key: 'dp-39', title: 'Palindrome Partitioning II', difficulty: 'Hard' },
      { key: 'dp-40', title: 'Partition Array for Maximum Sum', difficulty: 'Medium' },
      { key: 'dp-41', title: 'Maximum Rectangle Area with All 1s', difficulty: 'Hard' },
      { key: 'dp-42', title: 'Count Square Submatrices with All 1s', difficulty: 'Medium' },
      { key: 'dp-43', title: 'Best Time to Buy and Sell Stock I', difficulty: 'Easy' },
      { key: 'dp-44', title: 'Best Time to Buy and Sell Stock II', difficulty: 'Medium' },
      { key: 'dp-45', title: 'Best Time to Buy and Sell Stock III', difficulty: 'Hard' },
      { key: 'dp-46', title: 'Best Time to Buy and Sell Stock IV', difficulty: 'Hard' },
      { key: 'dp-47', title: 'Buy and Sell Stock with Cooldown', difficulty: 'Medium' },
      { key: 'dp-48', title: 'Buy and Sell Stock with Transaction Fee', difficulty: 'Medium' },
      { key: 'dp-49', title: 'Longest Palindromic Subsequence', difficulty: 'Medium' },
      { key: 'dp-50', title: 'Minimum Insertions to Make Palindrome', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Trie',
    icon: '🔠',
    color: 'hsl(280, 60%, 55%)',
    problems: [
      { key: 'trie-1', title: 'Implement Trie (Prefix Tree)', difficulty: 'Medium' },
      { key: 'trie-2', title: 'Implement Trie II (with Count)', difficulty: 'Medium' },
      { key: 'trie-3', title: 'Longest Word With All Prefixes', difficulty: 'Medium' },
      { key: 'trie-4', title: 'Number of Distinct Substrings', difficulty: 'Hard' },
      { key: 'trie-5', title: 'Power Set Using Trie', difficulty: 'Medium' },
      { key: 'trie-6', title: 'Maximum XOR of Two Numbers', difficulty: 'Medium' },
      { key: 'trie-7', title: 'Maximum XOR with Element from Array', difficulty: 'Hard' },
      { key: 'trie-8', title: 'Word Search II', difficulty: 'Hard' },
      { key: 'trie-9', title: 'Design Add and Search Words', difficulty: 'Medium' },
      { key: 'trie-10', title: 'Auto-Complete System', difficulty: 'Hard' },
    ],
  },
  {
    name: 'Sliding Window & Two Pointers',
    icon: '👆',
    color: 'hsl(180, 60%, 45%)',
    problems: [
      { key: 'sw-1', title: 'Maximum Sum Subarray of Size K', difficulty: 'Easy' },
      { key: 'sw-2', title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium' },
      { key: 'sw-3', title: 'Max Consecutive Ones III', difficulty: 'Medium' },
      { key: 'sw-4', title: 'Fruit Into Baskets', difficulty: 'Medium' },
      { key: 'sw-5', title: 'Longest Repeating Character Replacement', difficulty: 'Medium' },
      { key: 'sw-6', title: 'Binary Subarray with Sum', difficulty: 'Medium' },
      { key: 'sw-7', title: 'Count Nice Subarrays', difficulty: 'Medium' },
      { key: 'sw-8', title: 'Number of Substrings with All Three Characters', difficulty: 'Medium' },
      { key: 'sw-9', title: 'Minimum Window Substring', difficulty: 'Hard' },
      { key: 'sw-10', title: 'Minimum Window Subsequence', difficulty: 'Hard' },
      { key: 'sw-11', title: 'Container With Most Water', difficulty: 'Medium' },
      { key: 'sw-12', title: 'Trapping Rain Water', difficulty: 'Hard' },
      { key: 'sw-13', title: '3Sum', difficulty: 'Medium' },
      { key: 'sw-14', title: '3Sum Closest', difficulty: 'Medium' },
      { key: 'sw-15', title: '4Sum', difficulty: 'Medium' },
      { key: 'sw-16', title: 'Subarray Product Less Than K', difficulty: 'Medium' },
      { key: 'sw-17', title: 'Subarrays with K Different Integers', difficulty: 'Hard' },
      { key: 'sw-18', title: 'Valid Palindrome', difficulty: 'Easy' },
      { key: 'sw-19', title: 'Two Sum II (Sorted Array)', difficulty: 'Medium' },
      { key: 'sw-20', title: 'Boats to Save People', difficulty: 'Medium' },
    ],
  },
  {
    name: 'Bit Manipulation',
    icon: '⚡',
    color: 'hsl(60, 70%, 45%)',
    problems: [
      { key: 'bit-1', title: 'Check if Ith Bit is Set', difficulty: 'Easy' },
      { key: 'bit-2', title: 'Check if Number is Odd/Even', difficulty: 'Easy' },
      { key: 'bit-3', title: 'Check if Power of Two', difficulty: 'Easy' },
      { key: 'bit-4', title: 'Count Set Bits', difficulty: 'Easy' },
      { key: 'bit-5', title: 'Set/Clear/Toggle Ith Bit', difficulty: 'Easy' },
      { key: 'bit-6', title: 'Swap Two Numbers', difficulty: 'Easy' },
      { key: 'bit-7', title: 'Divide Two Integers', difficulty: 'Medium' },
      { key: 'bit-8', title: 'Single Number', difficulty: 'Easy' },
      { key: 'bit-9', title: 'Single Number II (Appears 3 Times)', difficulty: 'Medium' },
      { key: 'bit-10', title: 'Single Number III (Two Unique)', difficulty: 'Medium' },
      { key: 'bit-11', title: 'XOR of Numbers in a Range', difficulty: 'Medium' },
      { key: 'bit-12', title: 'Power Set Using Bits', difficulty: 'Medium' },
      { key: 'bit-13', title: 'Find Two Numbers with Odd Occurrences', difficulty: 'Medium' },
      { key: 'bit-14', title: 'Minimum Bit Flips', difficulty: 'Easy' },
    ],
  },
  {
    name: 'Math & Number Theory',
    icon: '🔢',
    color: 'hsl(320, 60%, 50%)',
    problems: [
      { key: 'math-1', title: 'Count Primes (Sieve)', difficulty: 'Medium' },
      { key: 'math-2', title: 'GCD and LCM', difficulty: 'Easy' },
      { key: 'math-3', title: 'Modular Exponentiation', difficulty: 'Medium' },
      { key: 'math-4', title: 'Count Trailing Zeros in Factorial', difficulty: 'Easy' },
      { key: 'math-5', title: 'Print All Divisors', difficulty: 'Easy' },
      { key: 'math-6', title: 'Prime Factorization', difficulty: 'Medium' },
      { key: 'math-7', title: 'Check Armstrong Number', difficulty: 'Easy' },
      { key: 'math-8', title: 'Reverse Integer', difficulty: 'Medium' },
      { key: 'math-9', title: 'Palindrome Number', difficulty: 'Easy' },
      { key: 'math-10', title: 'Excel Sheet Column Number', difficulty: 'Easy' },
    ],
  },
];

export const getTotalProblems = () =>
  STRIVER_ROADMAP.reduce((sum, t) => sum + t.problems.length, 0);

export const getDifficultyColor = (d: string) =>
  d === 'Easy' ? 'text-success' : d === 'Medium' ? 'text-warning' : 'text-destructive';

export const getDifficultyBg = (d: string) =>
  d === 'Easy' ? 'bg-success/10 text-success border-success/20' : d === 'Medium' ? 'bg-warning/10 text-warning border-warning/20' : 'bg-destructive/10 text-destructive border-destructive/20';
