import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Search, BookOpen, Copy, Check } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';

interface CheatEntry {
  title: string;
  category: string;
  timeComplexity: string;
  spaceComplexity: string;
  keyPoints: string[];
  pseudocode: string;
  whenToUse: string;
}

const CHEAT_ENTRIES: CheatEntry[] = [
  // ─── SORTING ──────────────────────────────────────────────────────
  { title: 'Bubble Sort', category: 'Sorting', timeComplexity: 'O(n²)', spaceComplexity: 'O(1)', keyPoints: ['Compare adjacent elements & swap', 'Stable sort', 'Adaptive: O(n) if already sorted', 'Each pass bubbles largest to end', 'Good for small/nearly sorted data'], pseudocode: 'for i in 0..n-1:\n  swapped = false\n  for j in 0..n-i-2:\n    if arr[j] > arr[j+1]:\n      swap(arr[j], arr[j+1])\n      swapped = true\n  if !swapped: break', whenToUse: 'Educational, nearly sorted small arrays' },
  { title: 'Selection Sort', category: 'Sorting', timeComplexity: 'O(n²)', spaceComplexity: 'O(1)', keyPoints: ['Find minimum, place at front', 'Not stable (can be made stable)', 'Always O(n²) regardless of input', 'Minimum swaps: O(n)', 'In-place'], pseudocode: 'for i in 0..n-1:\n  minIdx = i\n  for j in i+1..n-1:\n    if arr[j] < arr[minIdx]:\n      minIdx = j\n  swap(arr[i], arr[minIdx])', whenToUse: 'When memory writes are expensive, small arrays' },
  { title: 'Insertion Sort', category: 'Sorting', timeComplexity: 'O(n²)', spaceComplexity: 'O(1)', keyPoints: ['Insert element in correct position', 'Stable & adaptive', 'O(n) for nearly sorted', 'Good for small arrays (used in TimSort)', 'Online: can sort stream of data'], pseudocode: 'for i in 1..n-1:\n  key = arr[i]\n  j = i - 1\n  while j >= 0 and arr[j] > key:\n    arr[j+1] = arr[j]\n    j--\n  arr[j+1] = key', whenToUse: 'Small arrays, nearly sorted data, online sorting, hybrid sort base case' },
  { title: 'Merge Sort', category: 'Sorting', timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', keyPoints: ['Stable sort', 'Divide and conquer', 'Always O(n log n)', 'Good for linked lists', 'Counts inversions'], pseudocode: 'def mergesort(arr, l, r):\n  if l >= r: return\n  mid = (l+r)/2\n  mergesort(arr, l, mid)\n  mergesort(arr, mid+1, r)\n  merge(arr, l, mid, r)\n\ndef merge(arr, l, m, r):\n  // merge two sorted halves\n  // use temp array, copy back', whenToUse: 'Stable sort needed, linked lists, counting inversions, external sorting' },
  { title: 'Quick Sort', category: 'Sorting', timeComplexity: 'O(n log n) avg', spaceComplexity: 'O(log n)', keyPoints: ['In-place, not stable', 'Pivot selection matters (randomize!)', 'O(n²) worst case', 'Cache-friendly', '3-way partition for duplicates'], pseudocode: 'def quicksort(arr, lo, hi):\n  if lo < hi:\n    p = partition(arr, lo, hi)\n    quicksort(arr, lo, p-1)\n    quicksort(arr, p+1, hi)\n\ndef partition(arr, lo, hi):\n  pivot = arr[hi]; i = lo-1\n  for j in lo..hi-1:\n    if arr[j] <= pivot:\n      i++; swap(arr[i], arr[j])\n  swap(arr[i+1], arr[hi])\n  return i+1', whenToUse: 'General purpose, in-place sorting, cache performance matters' },
  { title: 'Heap Sort', category: 'Sorting', timeComplexity: 'O(n log n)', spaceComplexity: 'O(1)', keyPoints: ['In-place, not stable', 'Build max-heap, extract max repeatedly', 'Always O(n log n)', 'Good when memory is limited', 'Not cache-friendly'], pseudocode: 'def heapsort(arr):\n  for i in n/2-1 down to 0:\n    heapify(arr, n, i)\n  for i in n-1 down to 1:\n    swap(arr[0], arr[i])\n    heapify(arr, i, 0)\n\ndef heapify(arr, n, i):\n  largest = i; l=2*i+1; r=2*i+2\n  if l<n and arr[l]>arr[largest]: largest=l\n  if r<n and arr[r]>arr[largest]: largest=r\n  if largest!=i: swap; heapify(arr,n,largest)', whenToUse: 'Guaranteed O(n log n), in-place, memory constrained' },
  { title: 'Counting Sort', category: 'Sorting', timeComplexity: 'O(n + k)', spaceComplexity: 'O(k)', keyPoints: ['Non-comparison sort', 'Works for integers in known range', 'Stable', 'k = range of values', 'Used as subroutine in Radix Sort'], pseudocode: 'count = array of size (max-min+1)\nfor x in arr: count[x-min]++\nfor i in 1..k: count[i] += count[i-1]\nfor x in arr (reverse):\n  output[count[x-min]-1] = x\n  count[x-min]--', whenToUse: 'Integers with small range, as subroutine for radix sort' },
  { title: 'Radix Sort', category: 'Sorting', timeComplexity: 'O(d*(n+k))', spaceComplexity: 'O(n+k)', keyPoints: ['Non-comparison sort', 'Sort digit by digit (LSD or MSD)', 'Uses stable sort (counting) per digit', 'd = number of digits, k = base', 'Works for integers and strings'], pseudocode: 'def radixsort(arr):\n  maxVal = max(arr)\n  exp = 1\n  while maxVal / exp > 0:\n    countingSortByDigit(arr, exp)\n    exp *= 10', whenToUse: 'Large arrays of integers/strings with fixed length keys' },
  { title: 'Dutch National Flag', category: 'Sorting', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', keyPoints: ['3-way partition: 0s, 1s, 2s', 'Three pointers: low, mid, high', 'Single pass through array', 'Extension of Lomuto partition', 'Key for Sort Colors (LC 75)'], pseudocode: 'low = 0, mid = 0, high = n-1\nwhile mid <= high:\n  if arr[mid] == 0:\n    swap(arr[low], arr[mid])\n    low++; mid++\n  elif arr[mid] == 1:\n    mid++\n  else:\n    swap(arr[mid], arr[high])\n    high--', whenToUse: 'Sort array of 0s, 1s, 2s; 3-way partitioning; Quick Sort with many duplicates' },

  // ─── SEARCH ───────────────────────────────────────────────────────
  { title: 'Binary Search', category: 'Search', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', keyPoints: ['Sorted array required', 'Divide search space by half', 'lo <= hi pattern', 'Watch for overflow: mid = lo + (hi-lo)/2', 'Variants: lower bound, upper bound, search on answer'], pseudocode: 'lo=0, hi=n-1\nwhile lo <= hi:\n  mid = lo + (hi-lo)/2\n  if arr[mid] == target: return mid\n  elif arr[mid] < target: lo = mid+1\n  else: hi = mid-1\nreturn -1', whenToUse: 'Sorted arrays, monotonic functions, minimize/maximize answer' },
  { title: 'Binary Search on Answer', category: 'Search', timeComplexity: 'O(n log range)', spaceComplexity: 'O(1)', keyPoints: ['Answer space is monotonic', 'Binary search the answer, check feasibility', 'Common in minimize max, maximize min', 'Feasibility check is key'], pseudocode: 'lo, hi = min_ans, max_ans\nwhile lo < hi:\n  mid = lo + (hi - lo) / 2\n  if feasible(mid):\n    hi = mid\n  else:\n    lo = mid + 1\nreturn lo', whenToUse: 'Minimize maximum, maximize minimum, allocation problems, kth smallest' },
  { title: 'Ternary Search', category: 'Search', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', keyPoints: ['For unimodal functions (one peak/valley)', 'Divides into 3 parts', 'Slightly slower than binary search', 'Cannot use binary search on non-monotonic'], pseudocode: 'lo, hi = start, end\nwhile hi - lo > epsilon:\n  m1 = lo + (hi-lo)/3\n  m2 = hi - (hi-lo)/3\n  if f(m1) < f(m2):\n    lo = m1\n  else:\n    hi = m2\nreturn lo', whenToUse: 'Finding peak of unimodal function, bitonic array maximum' },
  { title: 'Exponential Search', category: 'Search', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', keyPoints: ['Find range first, then binary search', 'Good for unbounded/infinite arrays', 'Double index each step: 1, 2, 4, 8...', 'Then binary search in [i/2, i]'], pseudocode: 'if arr[0] == target: return 0\ni = 1\nwhile i < n and arr[i] <= target:\n  i *= 2\nreturn binarySearch(arr, i/2, min(i, n-1))', whenToUse: 'Unbounded/infinite sorted arrays, element near beginning' },
  { title: 'Quickselect', category: 'Search', timeComplexity: 'O(n) avg', spaceComplexity: 'O(1)', keyPoints: ['Find kth smallest/largest', 'Like quicksort but only recurse one side', 'O(n) average, O(n²) worst', 'Randomized pivot for O(n) expected', 'Median of medians for O(n) worst case'], pseudocode: 'def quickselect(arr, lo, hi, k):\n  if lo == hi: return arr[lo]\n  pivotIdx = partition(arr, lo, hi)\n  if k == pivotIdx: return arr[k]\n  elif k < pivotIdx:\n    return quickselect(arr, lo, pivotIdx-1, k)\n  else:\n    return quickselect(arr, pivotIdx+1, hi, k)', whenToUse: 'Kth largest/smallest, median finding, order statistics' },

  // ─── PATTERNS ─────────────────────────────────────────────────────
  { title: 'Two Pointers', category: 'Patterns', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', keyPoints: ['Sorted array usually', 'One from each end or same direction', 'Good for pair/triplet sums', 'Remove duplicates in-place', 'Fast & slow pointers for cycle detection'], pseudocode: 'l=0, r=n-1\nwhile l < r:\n  sum = arr[l] + arr[r]\n  if sum == target: return [l, r]\n  elif sum < target: l++\n  else: r--', whenToUse: 'Pair sums, palindromes, container problems, sorted array operations' },
  { title: 'Sliding Window', category: 'Patterns', timeComplexity: 'O(n)', spaceComplexity: 'O(k)', keyPoints: ['Contiguous subarray/substring', 'Fixed or variable window', 'Track window state with map/set', 'Shrink when constraint violated'], pseudocode: 'l=0\nfor r in range(n):\n  add arr[r] to window\n  while window invalid:\n    remove arr[l], l++\n  update answer', whenToUse: 'Subarray/substring with constraints, max/min window, distinct elements' },
  { title: 'Fast & Slow Pointers (Floyd\'s)', category: 'Patterns', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', keyPoints: ['Floyd\'s cycle detection', 'Slow moves 1 step, fast moves 2', 'If cycle: they meet inside cycle', 'Find cycle start: reset slow to head', 'Also finds middle of linked list'], pseudocode: 'slow = fast = head\nwhile fast and fast.next:\n  slow = slow.next\n  fast = fast.next.next\n  if slow == fast:\n    slow = head\n    while slow != fast:\n      slow = slow.next\n      fast = fast.next\n    return slow  // cycle start', whenToUse: 'Cycle detection, find middle, happy number, linked list cycle start' },
  { title: 'Prefix Sum', category: 'Patterns', timeComplexity: 'O(n) build, O(1) query', spaceComplexity: 'O(n)', keyPoints: ['Range sum queries', 'prefix[i] = sum(arr[0..i-1])', 'Range [l,r] = prefix[r+1] - prefix[l]', '2D prefix sum for matrix', 'Combine with HashMap for subarray sum = k'], pseudocode: 'prefix = [0] * (n+1)\nfor i in range(n):\n  prefix[i+1] = prefix[i] + arr[i]\n\nsum = prefix[r+1] - prefix[l]\n\n// Subarray sum = k\ncount=0; curSum=0; map={0:1}\nfor x in arr:\n  curSum += x\n  count += map.get(curSum-k, 0)\n  map[curSum] = map.get(curSum,0)+1', whenToUse: 'Range sum queries, subarray sum equals k, equilibrium index' },
  { title: "Moore's Voting Algorithm", category: 'Patterns', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', keyPoints: ['Find majority element (> n/2)', 'Candidate + count approach', 'Cancel out different elements', 'Verify candidate in 2nd pass', 'Extended: find elements > n/3 (2 candidates)'], pseudocode: 'candidate = null; count = 0\nfor x in arr:\n  if count == 0:\n    candidate = x; count = 1\n  elif x == candidate:\n    count++\n  else:\n    count--\n// Verify: count occurrences\n\n// Extended for > n/3:\nc1=c2=null; cnt1=cnt2=0\nfor x in arr:\n  if x==c1: cnt1++\n  elif x==c2: cnt2++\n  elif cnt1==0: c1=x; cnt1=1\n  elif cnt2==0: c2=x; cnt2=1\n  else: cnt1--; cnt2--', whenToUse: 'Majority element, elements appearing > n/k times' },
  { title: 'Backtracking', category: 'Patterns', timeComplexity: 'O(k^n) typically', spaceComplexity: 'O(n)', keyPoints: ['Build solution incrementally', 'Prune invalid branches early', 'Permutations, combinations, subsets', 'N-Queens, Sudoku', 'Use visited array or swap technique'], pseudocode: 'def backtrack(state, choices):\n  if complete(state):\n    results.add(state.copy())\n    return\n  for choice in choices:\n    if valid(choice):\n      state.add(choice)\n      backtrack(state, remaining)\n      state.remove(choice)', whenToUse: 'Generate permutations/combinations, constraint satisfaction, puzzle solving' },
  { title: 'Monotonic Stack', category: 'Patterns', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', keyPoints: ['Next greater/smaller element', 'Stock span, histogram area', 'Stack maintains sorted order', 'Each element pushed/popped once', 'Increasing vs decreasing depends on problem'], pseudocode: 'stack = []\nresult = [-1] * n\nfor i in range(n):\n  while stack and arr[stack[-1]] < arr[i]:\n    idx = stack.pop()\n    result[idx] = arr[i]\n  stack.append(i)', whenToUse: 'Next greater/smaller element, largest rectangle, daily temperatures' },
  { title: 'Monotonic Queue', category: 'Patterns', timeComplexity: 'O(n)', spaceComplexity: 'O(k)', keyPoints: ['Sliding window max/min', 'Deque maintains decreasing/increasing order', 'Remove expired elements from front', 'Remove smaller/larger from back before adding', 'Each element added/removed once'], pseudocode: 'deque = []\nresult = []\nfor i in range(n):\n  while deque and deque[0] < i-k+1:\n    deque.popleft()\n  while deque and arr[deque[-1]] <= arr[i]:\n    deque.pop()\n  deque.append(i)\n  if i >= k-1:\n    result.append(arr[deque[0]])', whenToUse: 'Sliding window maximum/minimum, jump game, constrained subarray' },
  { title: 'Divide and Conquer', category: 'Patterns', timeComplexity: 'Varies', spaceComplexity: 'O(log n) stack', keyPoints: ['Split problem into subproblems', 'Solve recursively, combine results', 'Master theorem for complexity', 'Merge sort, quick sort, closest pair', 'Matrix multiplication (Strassen)'], pseudocode: 'def solve(problem):\n  if base_case(problem):\n    return trivial_solution\n  left, right = split(problem)\n  leftResult = solve(left)\n  rightResult = solve(right)\n  return combine(leftResult, rightResult)', whenToUse: 'Problems that can be split into independent subproblems' },
  { title: 'Bit Manipulation', category: 'Patterns', timeComplexity: 'O(1) per op', spaceComplexity: 'O(1)', keyPoints: ['XOR: a^a=0, a^0=a (find single)', 'Set bit: n | (1<<i)', 'Clear bit: n & ~(1<<i)', 'Check bit: n & (1<<i)', 'Count bits: Brian Kernighan n&(n-1)', 'Power of 2: n & (n-1) == 0'], pseudocode: '// Single number\nresult = 0\nfor x in arr: result ^= x\n\n// Count set bits\ncount = 0\nwhile n > 0:\n  n = n & (n-1)\n  count++\n\n// Subsets via bitmask\nfor mask in 0..(1<<n)-1:\n  for i in 0..n-1:\n    if mask & (1<<i): include arr[i]', whenToUse: 'Find unique element, subset generation, power of 2 checks, bit counting' },
  { title: 'Greedy', category: 'Patterns', timeComplexity: 'Varies', spaceComplexity: 'Varies', keyPoints: ['Locally optimal → globally optimal', 'Sort by some criteria first', 'Prove greedy choice property', 'Exchange argument for proofs', 'Interval scheduling, Huffman, coins'], pseudocode: '// Activity Selection\nsort by end time\nresult = [first]\nfor activity in rest:\n  if activity.start >= result[-1].end:\n    result.append(activity)\n\n// Fractional Knapsack\nsort by value/weight ratio\nfor item in sorted:\n  take as much as capacity allows', whenToUse: 'Interval scheduling, Huffman coding, minimum coins, job scheduling' },
  { title: 'Tortoise and Hare (Find Duplicate)', category: 'Patterns', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', keyPoints: ['Find duplicate in array (no modify)', 'Treat values as next pointers', 'Phase 1: detect cycle', 'Phase 2: find cycle entry = duplicate', 'Based on Floyd\'s cycle detection'], pseudocode: 'slow = fast = nums[0]\ndo:\n  slow = nums[slow]\n  fast = nums[nums[fast]]\nwhile slow != fast\n\nslow = nums[0]\nwhile slow != fast:\n  slow = nums[slow]\n  fast = nums[fast]\nreturn slow', whenToUse: 'Find duplicate number, linked list cycle, Floyd\'s algorithm' },

  // ─── DYNAMIC PROGRAMMING ──────────────────────────────────────────
  { title: 'Dynamic Programming (General)', category: 'DP', timeComplexity: 'Varies', spaceComplexity: 'Varies', keyPoints: ['Optimal substructure', 'Overlapping subproblems', 'Top-down (memo) or Bottom-up (tabulation)', 'Define state clearly', 'Space optimization with rolling array'], pseudocode: '// Bottom-up\ndp[0] = base_case\nfor i in 1..n:\n  dp[i] = recurrence(dp[i-1], ...)\nreturn dp[n]\n\n// Top-down\nmemo = {}\ndef solve(state):\n  if state in memo: return memo[state]\n  memo[state] = compute()\n  return memo[state]', whenToUse: 'Optimization problems, counting paths, string matching, knapsack' },
  { title: "Kadane's Algorithm", category: 'DP', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', keyPoints: ['Maximum subarray sum', 'Track current and global max', 'Reset current if negative', 'Track start/end indices', 'Circular variant: total - min subarray'], pseudocode: 'curMax = globalMax = arr[0]\nfor i in 1..n:\n  curMax = max(arr[i], curMax + arr[i])\n  globalMax = max(globalMax, curMax)\nreturn globalMax\n\n// Circular:\ncircularMax = max(normalMax, total - minSubarray)', whenToUse: 'Maximum subarray, maximum circular subarray, maximum product subarray' },
  { title: '0/1 Knapsack', category: 'DP', timeComplexity: 'O(n*W)', spaceComplexity: 'O(W)', keyPoints: ['Each item: take or skip', 'dp[i][w] = max value with i items, capacity w', 'Space optimize to 1D: iterate W backwards', 'Variations: subset sum, equal partition', 'Bounded knapsack: binary representation'], pseudocode: 'dp = [0] * (W+1)\nfor i in 0..n-1:\n  for w in W down to wt[i]:\n    dp[w] = max(dp[w], dp[w-wt[i]] + val[i])\nreturn dp[W]\n\n// Subset sum:\ndp = [false] * (target+1)\ndp[0] = true\nfor x in arr:\n  for s in target down to x:\n    dp[s] = dp[s] || dp[s-x]', whenToUse: 'Knapsack, subset sum, equal partition, target sum, coin change (bounded)' },
  { title: 'Unbounded Knapsack', category: 'DP', timeComplexity: 'O(n*W)', spaceComplexity: 'O(W)', keyPoints: ['Items can be used unlimited times', 'Iterate W forwards (unlike 0/1)', 'Coin change: minimum coins', 'Rod cutting problem', 'Combinations vs permutations ordering'], pseudocode: '// Coin Change (min coins)\ndp = [INF] * (amount+1)\ndp[0] = 0\nfor coin in coins:\n  for a in coin..amount:\n    dp[a] = min(dp[a], dp[a-coin]+1)\n\n// Count ways\ndp = [0] * (amount+1)\ndp[0] = 1\nfor coin in coins:\n  for a in coin..amount:\n    dp[a] += dp[a-coin]', whenToUse: 'Coin change, rod cutting, unlimited item selection' },
  { title: 'LCS (Longest Common Subsequence)', category: 'DP', timeComplexity: 'O(m*n)', spaceComplexity: 'O(m*n)', keyPoints: ['Compare two strings/arrays', 'dp[i][j] = LCS of s1[0..i-1] and s2[0..j-1]', 'If match: dp[i-1][j-1]+1, else max', 'Reconstruct path by backtracking', 'Space optimize to 2 rows'], pseudocode: 'dp = 2D (m+1) x (n+1)\nfor i in 1..m:\n  for j in 1..n:\n    if s1[i-1] == s2[j-1]:\n      dp[i][j] = dp[i-1][j-1] + 1\n    else:\n      dp[i][j] = max(dp[i-1][j], dp[i][j-1])\nreturn dp[m][n]', whenToUse: 'String comparison, diff tools, edit distance, shortest common supersequence' },
  { title: 'LIS (Longest Increasing Subsequence)', category: 'DP', timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', keyPoints: ['O(n²) DP or O(n log n) with patience sort', 'Maintain tails array of smallest end elements', 'Binary search to find position', 'Can reconstruct the actual subsequence', 'Variations: non-decreasing, longest chain'], pseudocode: 'tails = []\nfor x in arr:\n  pos = bisect_left(tails, x)\n  if pos == len(tails):\n    tails.append(x)\n  else:\n    tails[pos] = x\nreturn len(tails)', whenToUse: 'Longest increasing subsequence, box stacking, envelope nesting' },
  { title: 'Edit Distance', category: 'DP', timeComplexity: 'O(m*n)', spaceComplexity: 'O(m*n)', keyPoints: ['Levenshtein distance', 'Operations: insert, delete, replace', 'dp[i][j] = min edits for s1[0..i-1] → s2[0..j-1]', 'If chars match: dp[i-1][j-1]', 'Else: 1 + min(insert, delete, replace)'], pseudocode: 'dp = 2D (m+1) x (n+1)\nfor i in 0..m: dp[i][0] = i\nfor j in 0..n: dp[0][j] = j\nfor i in 1..m:\n  for j in 1..n:\n    if s1[i-1] == s2[j-1]:\n      dp[i][j] = dp[i-1][j-1]\n    else:\n      dp[i][j] = 1 + min(\n        dp[i-1][j],\n        dp[i][j-1],\n        dp[i-1][j-1])', whenToUse: 'Spell checker, DNA alignment, fuzzy matching' },
  { title: 'Matrix Chain Multiplication', category: 'DP', timeComplexity: 'O(n³)', spaceComplexity: 'O(n²)', keyPoints: ['Optimal parenthesization', 'dp[i][j] = min cost to multiply matrices i..j', 'Try all split points k between i and j', 'Interval DP pattern', 'Similar: burst balloons, palindrome partition'], pseudocode: 'dp = 2D n x n (all 0)\nfor len in 2..n:\n  for i in 0..n-len:\n    j = i + len - 1\n    dp[i][j] = INF\n    for k in i..j-1:\n      cost = dp[i][k] + dp[k+1][j]\n           + dims[i]*dims[k+1]*dims[j+1]\n      dp[i][j] = min(dp[i][j], cost)', whenToUse: 'Optimal parenthesization, burst balloons, palindrome partitioning' },
  { title: 'DP on Trees', category: 'DP', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', keyPoints: ['DFS-based, compute children first', 'Re-rooting technique for all-root answers', 'Common: diameter, max path sum', 'In/Out DP for parent contribution', 'Subtree aggregation'], pseudocode: 'def dfs(node, parent):\n  maxD1 = maxD2 = 0\n  for child of node:\n    if child == parent: continue\n    d = dfs(child, node) + 1\n    if d > maxD1:\n      maxD2 = maxD1; maxD1 = d\n    elif d > maxD2:\n      maxD2 = d\n  diameter = max(diameter, maxD1+maxD2)\n  return maxD1', whenToUse: 'Tree diameter, max path sum, subtree queries, re-rooting problems' },
  { title: 'Bitmask DP', category: 'DP', timeComplexity: 'O(2^n * n)', spaceComplexity: 'O(2^n)', keyPoints: ['State = bitmask of visited/selected', 'Usually n ≤ 20', 'TSP, assignment problem', 'dp[mask] = best result using elements in mask', 'Iterate over submasks: s=(s-1)&mask'], pseudocode: '// TSP\ndp = [2^n][n] = INF\ndp[1][0] = 0\nfor mask in 1..2^n-1:\n  for u in 0..n-1:\n    if !(mask & (1<<u)): continue\n    for v in 0..n-1:\n      if mask & (1<<v): continue\n      newMask = mask | (1<<v)\n      dp[newMask][v] = min(\n        dp[newMask][v],\n        dp[mask][u] + dist[u][v])', whenToUse: 'TSP, assignment, subset problems with n ≤ 20, Hamiltonian path' },
  { title: 'Digit DP', category: 'DP', timeComplexity: 'O(digits * states)', spaceComplexity: 'O(digits * states)', keyPoints: ['Count numbers in range with property', 'Process digit by digit, track constraints', 'tight flag: still bounded by limit', 'Common states: sum of digits, remainder', 'Range [L,R] = f(R) - f(L-1)'], pseudocode: 'def digitDP(pos, tight, state, digits):\n  if pos == len(digits): return valid?\n  if memo[pos][tight][state]: return it\n  limit = digits[pos] if tight else 9\n  result = 0\n  for d in 0..limit:\n    result += digitDP(\n      pos+1, tight && d==limit,\n      update(state, d), digits)\n  return memo[pos][tight][state] = result', whenToUse: 'Count numbers with digit sum, divisibility, digit patterns in range' },

  // ─── GRAPH ALGORITHMS ─────────────────────────────────────────────
  { title: 'BFS (Breadth-First Search)', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['Uses Queue', 'Level-order traversal', 'Shortest path (unweighted)', 'Mark visited BEFORE enqueue', 'Multi-source BFS for multiple starting points'], pseudocode: 'queue = [start]\nvisited = {start}\nwhile queue:\n  node = queue.popleft()\n  for neighbor of node:\n    if not visited:\n      visited.add(neighbor)\n      queue.append(neighbor)', whenToUse: 'Shortest path (unweighted), level-order, nearest/closest problems' },
  { title: 'DFS (Depth-First Search)', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['Uses Stack/Recursion', 'Goes deep first', 'Detect cycles, topological sort', 'Pre/In/Post order', 'Connected components'], pseudocode: 'def dfs(node, visited):\n  visited.add(node)\n  for neighbor of node:\n    if not visited:\n      dfs(neighbor, visited)\n\n// Iterative\nstack = [start]\nwhile stack:\n  node = stack.pop()\n  if visited: continue\n  visited.add(node)\n  for neighbor: stack.push(neighbor)', whenToUse: 'Connectivity, cycle detection, topological sort, path finding' },
  { title: 'Dijkstra\'s Algorithm', category: 'Graphs', timeComplexity: 'O((V+E)logV)', spaceComplexity: 'O(V)', keyPoints: ['Shortest path (weighted, non-negative)', 'Min-heap / Priority Queue', 'Greedy approach', 'Relax edges', 'Skip outdated entries in heap'], pseudocode: 'dist = {all: INF}; dist[start] = 0\npq = [(0, start)]\nwhile pq:\n  d, u = heappop(pq)\n  if d > dist[u]: continue\n  for v, w in adj[u]:\n    if d+w < dist[v]:\n      dist[v] = d+w\n      heappush(pq, (d+w, v))', whenToUse: 'Weighted shortest path (non-negative edges), network routing' },
  { title: 'Bellman-Ford', category: 'Graphs', timeComplexity: 'O(V*E)', spaceComplexity: 'O(V)', keyPoints: ['Handles negative weights', 'Detects negative cycles', 'Relax all edges V-1 times', 'If Vth relaxation changes dist → negative cycle', 'Slower than Dijkstra but more general'], pseudocode: 'dist = [INF] * V; dist[src] = 0\nfor i in 1..V-1:\n  for each edge (u, v, w):\n    if dist[u]+w < dist[v]:\n      dist[v] = dist[u]+w\n// Check negative cycle\nfor each edge (u, v, w):\n  if dist[u]+w < dist[v]:\n    print("Negative cycle!")', whenToUse: 'Negative weights, detect negative cycles, currency arbitrage' },
  { title: 'Floyd-Warshall', category: 'Graphs', timeComplexity: 'O(V³)', spaceComplexity: 'O(V²)', keyPoints: ['All-pairs shortest path', 'DP on intermediate vertices', 'Handles negative weights (no neg cycles)', 'Can detect negative cycles: dist[i][i] < 0', 'Dense graphs preferred'], pseudocode: 'dist = adjacency matrix\nfor k in 0..V-1:\n  for i in 0..V-1:\n    for j in 0..V-1:\n      dist[i][j] = min(\n        dist[i][j],\n        dist[i][k] + dist[k][j])', whenToUse: 'All-pairs shortest path, transitive closure, detect negative cycles' },
  { title: 'Topological Sort (Kahn\'s BFS)', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['DAG only', 'BFS with in-degree array', 'Detects cycles', 'Multiple valid orderings possible', 'Used for task scheduling'], pseudocode: 'indegree = count incoming edges\nqueue = [nodes with indegree 0]\nresult = []\nwhile queue:\n  node = queue.popleft()\n  result.append(node)\n  for neighbor:\n    indegree[neighbor]--\n    if indegree[neighbor]==0:\n      queue.append(neighbor)\nif len(result) != V: CYCLE!', whenToUse: 'Task ordering, course scheduling, build systems, dependency resolution' },
  { title: 'Topological Sort (DFS)', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['DFS-based approach', 'Push to stack after visiting all neighbors', 'Reverse of finish order', 'Can detect cycles with coloring', 'WHITE/GRAY/BLACK coloring'], pseudocode: 'stack = []; visited = set()\ndef dfs(node):\n  visited.add(node)\n  for neighbor of node:\n    if not visited: dfs(neighbor)\n  stack.append(node)\n\nfor node in all_nodes:\n  if not visited: dfs(node)\nresult = stack.reversed()', whenToUse: 'Task ordering, DFS-based, when Kahn\'s is not preferred' },
  { title: 'Kruskal\'s MST', category: 'Graphs', timeComplexity: 'O(E log E)', spaceComplexity: 'O(V)', keyPoints: ['Minimum Spanning Tree', 'Sort edges by weight', 'Use Union-Find to add edges', 'Skip edges that create cycle', 'Greedy: always pick lightest safe edge'], pseudocode: 'sort edges by weight\nuf = UnionFind(V)\nmst = []\nfor (u, v, w) in sorted_edges:\n  if find(u) != find(v):\n    union(u, v)\n    mst.append((u, v, w))\n    if len(mst) == V-1: break', whenToUse: 'MST, sparse graphs, when edges are given explicitly' },
  { title: 'Prim\'s MST', category: 'Graphs', timeComplexity: 'O((V+E)logV)', spaceComplexity: 'O(V)', keyPoints: ['Minimum Spanning Tree', 'Grow tree from a starting node', 'Min-heap to pick lightest edge', 'Similar to Dijkstra', 'Better for dense graphs'], pseudocode: 'visited = set(); pq = [(0, start)]\ntotal = 0\nwhile pq and len(visited) < V:\n  w, u = heappop(pq)\n  if u in visited: continue\n  visited.add(u); total += w\n  for v, weight in adj[u]:\n    if v not in visited:\n      heappush(pq, (weight, v))', whenToUse: 'MST, dense graphs, adjacency list representation' },
  { title: 'Tarjan\'s SCC', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['Strongly Connected Components', 'DFS with discovery/low-link values', 'Stack-based, single pass', 'low[u] = min reachable ancestor', 'SCC root when disc[u] == low[u]'], pseudocode: 'disc = low = [-1] * V\nstack = []; onStack = set()\ntimer = 0\ndef tarjan(u):\n  disc[u] = low[u] = timer++\n  stack.push(u); onStack.add(u)\n  for v in adj[u]:\n    if disc[v]==-1:\n      tarjan(v)\n      low[u] = min(low[u], low[v])\n    elif v in onStack:\n      low[u] = min(low[u], disc[v])\n  if disc[u] == low[u]:\n    // pop SCC until u', whenToUse: 'Strongly connected components, 2-SAT, condensation graph' },
  { title: 'Kosaraju\'s SCC', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['Two DFS passes', '1st: fill stack by finish time', '2nd: DFS on transposed graph', 'Easier than Tarjan', 'Needs reverse graph'], pseudocode: '// Pass 1: Fill stack\nfor node in all:\n  if not visited: dfs1(node)\n  // push after neighbors done\n\n// Pass 2: Reverse graph\nvisited.clear()\nwhile stack:\n  node = stack.pop()\n  if not visited:\n    dfs2_reverse(node)  // one SCC', whenToUse: 'Strongly connected components, simpler implementation' },
  { title: 'Bridges & Articulation Points', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['Bridge: edge removal disconnects graph', 'Articulation point: vertex removal disconnects', 'DFS with disc/low arrays', 'Bridge: low[v] > disc[u]', 'Art point: low[v] >= disc[u]'], pseudocode: 'def dfs(u, parent):\n  disc[u] = low[u] = timer++\n  for v in adj[u]:\n    if v == parent: continue\n    if disc[v] == -1:\n      dfs(v, u)\n      low[u] = min(low[u], low[v])\n      if low[v] > disc[u]:\n        bridges.add((u, v))\n    else:\n      low[u] = min(low[u], disc[v])', whenToUse: 'Network reliability, critical connections, vulnerable edges/nodes' },
  { title: 'A* Search', category: 'Graphs', timeComplexity: 'O(E log V)', spaceComplexity: 'O(V)', keyPoints: ['Informed search with heuristic', 'f(n) = g(n) + h(n)', 'g = actual cost, h = heuristic', 'Heuristic must be admissible', 'Optimal if consistent'], pseudocode: 'openSet = PQ [(f(start), start)]\ng = {start: 0}\nwhile openSet:\n  _, curr = openSet.pop()\n  if curr == goal: return path\n  for nbr, cost in adj[curr]:\n    tentG = g[curr] + cost\n    if tentG < g.get(nbr, INF):\n      g[nbr] = tentG\n      f = tentG + heuristic(nbr, goal)\n      openSet.push((f, nbr))', whenToUse: 'Pathfinding with heuristics, game AI, maze solving, GPS' },
  { title: 'Bipartite Check (BFS Coloring)', category: 'Graphs', timeComplexity: 'O(V+E)', spaceComplexity: 'O(V)', keyPoints: ['2-color the graph', 'BFS/DFS assigning alternating colors', 'Same color neighbor → not bipartite', 'Odd-length cycle → not bipartite', 'Used in matching problems'], pseudocode: 'color = [-1] * V\nfor start in 0..V-1:\n  if color[start] != -1: continue\n  queue = [start]; color[start] = 0\n  while queue:\n    u = queue.popleft()\n    for v in adj[u]:\n      if color[v]==-1:\n        color[v] = 1-color[u]\n        queue.append(v)\n      elif color[v]==color[u]:\n        return false', whenToUse: 'Graph coloring, matching, 2-colorable check' },

  // ─── DATA STRUCTURES ──────────────────────────────────────────────
  { title: 'Union-Find (DSU)', category: 'Data Structures', timeComplexity: 'O(α(n)) ≈ O(1)', spaceComplexity: 'O(n)', keyPoints: ['Connected components', 'Path compression + union by rank', 'Kruskal\'s MST', 'Cycle detection', 'Count components'], pseudocode: 'parent = [i for i in range(n)]\nrank = [0] * n\ndef find(x):\n  if parent[x] != x:\n    parent[x] = find(parent[x])\n  return parent[x]\ndef union(x, y):\n  px, py = find(x), find(y)\n  if px == py: return false\n  if rank[px]<rank[py]: swap\n  parent[py] = px\n  if rank[px]==rank[py]: rank[px]++\n  return true', whenToUse: 'Connected components, MST, dynamic connectivity' },
  { title: 'Trie (Prefix Tree)', category: 'Data Structures', timeComplexity: 'O(L) per op', spaceComplexity: 'O(N*L)', keyPoints: ['Prefix tree', 'Autocomplete, spell check', 'children map + isEnd flag', 'Store count at each node', 'Wildcard search with DFS'], pseudocode: 'class TrieNode:\n  children = {}\n  isEnd = false\n\ndef insert(word):\n  node = root\n  for ch in word:\n    if ch not in children:\n      children[ch] = TrieNode()\n    node = children[ch]\n  node.isEnd = true\n\ndef search(word):\n  node = root\n  for ch in word:\n    if ch not in children: return false\n    node = children[ch]\n  return node.isEnd', whenToUse: 'Prefix matching, autocomplete, word search, IP routing' },
  { title: 'Segment Tree', category: 'Data Structures', timeComplexity: 'O(log n) query/update', spaceComplexity: 'O(n)', keyPoints: ['Range queries + point/range updates', 'Build O(n), query/update O(log n)', 'Lazy propagation for range updates', 'Sum, min, max, GCD queries', 'Node stores aggregate of range'], pseudocode: 'tree = [0] * (4*n)\ndef build(node, l, r):\n  if l==r: tree[node]=arr[l]; return\n  mid=(l+r)/2\n  build(2*node,l,mid)\n  build(2*node+1,mid+1,r)\n  tree[node]=tree[2*node]+tree[2*node+1]\n\ndef query(node,l,r,ql,qr):\n  if ql>r or qr<l: return 0\n  if ql<=l and r<=qr: return tree[node]\n  return query(left)+query(right)\n\ndef update(node,l,r,idx,val):\n  if l==r: tree[node]=val; return\n  recurse; tree[node]=left+right', whenToUse: 'Range sum/min/max, range updates, count inversions' },
  { title: 'Binary Indexed Tree (Fenwick)', category: 'Data Structures', timeComplexity: 'O(log n) query/update', spaceComplexity: 'O(n)', keyPoints: ['Prefix sums with point updates', 'Simpler than segment tree', 'Uses bit manipulation: i & (-i)', 'Update: add to ancestors', 'Query: sum from 1 to index'], pseudocode: 'bit = [0] * (n+1)\ndef update(i, delta):\n  while i <= n:\n    bit[i] += delta\n    i += i & (-i)\n\ndef query(i):\n  s = 0\n  while i > 0:\n    s += bit[i]\n    i -= i & (-i)\n  return s\n\nrangeSum = query(r) - query(l-1)', whenToUse: 'Prefix sums with updates, count inversions, simpler than segment tree' },
  { title: 'Heap / Priority Queue', category: 'Data Structures', timeComplexity: 'O(log n) ins/del', spaceComplexity: 'O(n)', keyPoints: ['Top-K problems', 'Merge K sorted lists', 'Median in stream (two heaps)', 'Kth largest: min-heap of size k', 'Custom comparator'], pseudocode: '// Top K Frequent\ncount = Counter(nums); heap = []\nfor key, freq in count:\n  heappush(heap, (freq, key))\n  if len(heap) > k: heappop(heap)\n\n// Running Median\nmaxHeap=[]  minHeap=[]\ndef addNum(num):\n  heappush(maxHeap, -num)\n  heappush(minHeap, -heappop(maxHeap))\n  if len(minHeap)>len(maxHeap):\n    heappush(maxHeap, -heappop(minHeap))\ndef median(): return -maxHeap[0]', whenToUse: 'Top-K, merge K lists, running median, shortest path, scheduling' },
  { title: 'LRU Cache', category: 'Data Structures', timeComplexity: 'O(1) get/put', spaceComplexity: 'O(capacity)', keyPoints: ['HashMap + Doubly Linked List', 'Get: move to front (MRU)', 'Put: add to front, evict from back (LRU)', 'Sentinel head/tail nodes simplify code', 'LinkedHashMap in Java'], pseudocode: 'class LRUCache:\n  map = {}; head <-> tail\n\n  def get(key):\n    if key not in map: return -1\n    moveToFront(map[key])\n    return map[key].val\n\n  def put(key, val):\n    if key in map:\n      update & moveToFront\n    else:\n      if full: evict tail.prev\n      addToFront(new Node)\n      map[key] = node', whenToUse: 'Cache, page replacement, recent items tracking' },
  { title: 'Stack (Applications)', category: 'Data Structures', timeComplexity: 'O(1) per op', spaceComplexity: 'O(n)', keyPoints: ['LIFO: Last In First Out', 'Valid parentheses', 'Evaluate postfix expressions', 'Min stack: track min at each level', 'Implement queue using 2 stacks'], pseudocode: '// Valid Parentheses\nstack = []\nfor ch in s:\n  if ch in "({[": stack.push(ch)\n  else:\n    if empty or !match: return false\n    stack.pop()\nreturn stack empty\n\n// Min Stack\nstack = []  // (val, curMin)\ndef push(x):\n  minVal = min(x, stack[-1][1]) if stack else x\n  stack.append((x, minVal))\ndef getMin(): return stack[-1][1]', whenToUse: 'Parentheses matching, expression evaluation, undo, min/max tracking' },
  { title: 'Queue & Deque', category: 'Data Structures', timeComplexity: 'O(1) per op', spaceComplexity: 'O(n)', keyPoints: ['FIFO: First In First Out', 'Deque: double-ended queue', 'BFS traversal', 'Implement stack using queues', 'Circular queue for fixed size'], pseudocode: '// Stack using Queues\nclass MyStack:\n  q = Queue()\n  def push(x):\n    q.add(x)\n    for i in 0..q.size()-2:\n      q.add(q.poll())\n  def pop(): return q.poll()\n  def top(): return q.peek()', whenToUse: 'BFS, task scheduling, sliding window, producer-consumer' },

  // ─── STRING ALGORITHMS ────────────────────────────────────────────
  { title: 'KMP (Knuth-Morris-Pratt)', category: 'Strings', timeComplexity: 'O(n+m)', spaceComplexity: 'O(m)', keyPoints: ['Pattern matching in O(n+m)', 'Build failure/LPS array', 'LPS[i] = longest proper prefix = suffix', 'Never re-compare matched chars', 'Key: preprocess pattern'], pseudocode: '// Build LPS\nlps = [0]*m; len=0; i=1\nwhile i < m:\n  if pat[i]==pat[len]:\n    len++; lps[i]=len; i++\n  else:\n    if len>0: len=lps[len-1]\n    else: lps[i]=0; i++\n\n// Search\ni=j=0\nwhile i < n:\n  if text[i]==pat[j]: i++; j++\n  if j==m: found at i-j; j=lps[j-1]\n  elif i<n and text[i]!=pat[j]:\n    if j>0: j=lps[j-1] else: i++', whenToUse: 'Pattern matching, repeated pattern detection, string periodicity' },
  { title: 'Rabin-Karp', category: 'Strings', timeComplexity: 'O(n+m) avg', spaceComplexity: 'O(1)', keyPoints: ['Rolling hash for pattern matching', 'Hash collision → verify actual comparison', 'Multiple pattern search', 'Choose good prime and base', 'Plagiarism detection'], pseudocode: 'base=31; mod=1e9+7\npatHash = hash(pattern)\nwinHash = hash(text[0..m-1])\nfor i in 0..n-m:\n  if winHash == patHash:\n    if text[i..i+m-1] == pattern: found!\n  // Roll hash\n  winHash = (winHash-text[i]*basePow)\n           *base + text[i+m]', whenToUse: 'Multiple pattern search, string matching, plagiarism detection' },
  { title: 'Z-Algorithm', category: 'Strings', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', keyPoints: ['Z[i] = longest match with prefix at pos i', 'Concat pattern + "$" + text', 'Z[i] == m means pattern found', 'Maintain [L, R] window', 'Alternative to KMP'], pseudocode: 'z = [0]*n; z[0]=n; L=R=0\nfor i in 1..n-1:\n  if i < R: z[i] = min(R-i, z[i-L])\n  while i+z[i]<n and s[z[i]]==s[i+z[i]]:\n    z[i]++\n  if i+z[i] > R: L=i; R=i+z[i]\n\n// Pattern match: s = pat+"$"+text', whenToUse: 'Pattern matching, string periodicity, distinct substrings' },
  { title: 'Manacher\'s Algorithm', category: 'Strings', timeComplexity: 'O(n)', spaceComplexity: 'O(n)', keyPoints: ['All palindromic substrings in O(n)', 'Transform: insert # between chars', 'P[i] = radius of palindrome at i', 'Mirror property to skip work', 'Longest palindromic substring'], pseudocode: 't = "^#" + "#".join(s) + "#$"\np = [0]*len(t); c=r=0\nfor i in 1..len(t)-2:\n  mirror = 2*c-i\n  if i<r: p[i]=min(r-i, p[mirror])\n  while t[i+p[i]+1]==t[i-p[i]-1]:\n    p[i]++\n  if i+p[i]>r: c=i; r=i+p[i]\n// max(p) = longest palindrome length', whenToUse: 'Longest palindromic substring, count palindromic substrings' },
  { title: 'Suffix Array', category: 'Strings', timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', keyPoints: ['Sorted array of all suffixes', 'LCP array for common prefixes', 'Build with sort + doubling', 'Replaces suffix tree', 'Binary search for queries'], pseudocode: '// Construction\nsuffixes = [(s[i:], i) for i in range(n)]\nsuffixes.sort()\nsa = [idx for (_, idx) in suffixes]\n\n// LCP (Kasai\'s)\nrank = inverse of sa\nlcp=[0]*n; k=0\nfor i in 0..n-1:\n  if rank[i]==0: k=0; continue\n  j = sa[rank[i]-1]\n  while s[i+k]==s[j+k]: k++\n  lcp[rank[i]]=k\n  if k>0: k--', whenToUse: 'Substring search, longest repeated substring, distinct substrings' },

  // ─── TREE ALGORITHMS ──────────────────────────────────────────────
  { title: 'Binary Tree Traversals', category: 'Trees', timeComplexity: 'O(n)', spaceComplexity: 'O(h)', keyPoints: ['Inorder: Left, Root, Right (BST → sorted)', 'Preorder: Root, Left, Right (serialize)', 'Postorder: Left, Right, Root (delete)', 'Level-order: BFS with queue', 'Morris traversal: O(1) space'], pseudocode: '// Inorder (iterative)\nstack=[]; curr=root\nwhile curr or stack:\n  while curr: stack.push(curr); curr=curr.left\n  curr=stack.pop(); visit(curr)\n  curr=curr.right\n\n// Morris Inorder (O(1) space)\ncurr=root\nwhile curr:\n  if !curr.left: visit(curr); curr=curr.right\n  else:\n    pred=curr.left\n    while pred.right and pred.right!=curr:\n      pred=pred.right\n    if !pred.right: pred.right=curr; curr=curr.left\n    else: pred.right=null; visit(curr); curr=curr.right', whenToUse: 'Tree processing, serialization, BST validation, expression trees' },
  { title: 'BST Operations', category: 'Trees', timeComplexity: 'O(h) per op', spaceComplexity: 'O(h)', keyPoints: ['Search, Insert, Delete: O(h)', 'Inorder gives sorted order', 'Delete: 0/1/2 children cases', '2 children: replace with inorder successor', 'Balanced BST: h = O(log n)'], pseudocode: 'def search(root, key):\n  if !root or root.val==key: return root\n  if key<root.val: return search(root.left)\n  return search(root.right)\n\ndef insert(root, key):\n  if !root: return new Node(key)\n  if key<root.val: root.left=insert(root.left)\n  else: root.right=insert(root.right)\n  return root', whenToUse: 'Dynamic sorted data, range queries, order statistics' },
  { title: 'Lowest Common Ancestor (LCA)', category: 'Trees', timeComplexity: 'O(log n) query', spaceComplexity: 'O(n log n)', keyPoints: ['Binary lifting with sparse table', 'Preprocess: O(n log n)', 'Query: O(log n)', 'For BST: simpler O(h)', 'Euler tour + RMQ alternative'], pseudocode: 'up = [n][LOG]\ndef preprocess(root):\n  // DFS: up[v][0] = parent\n  for k in 1..LOG:\n    up[v][k] = up[up[v][k-1]][k-1]\n\ndef lca(u, v):\n  // Make same depth\n  diff = depth[u]-depth[v]\n  for k: if diff&(1<<k): u=up[u][k]\n  if u==v: return u\n  for k in LOG..0:\n    if up[u][k]!=up[v][k]:\n      u=up[u][k]; v=up[v][k]\n  return up[u][0]', whenToUse: 'Tree path queries, distance between nodes, tree DP' },

  // ─── MATH / NUMBER THEORY ─────────────────────────────────────────
  { title: 'Sieve of Eratosthenes', category: 'Math', timeComplexity: 'O(n log log n)', spaceComplexity: 'O(n)', keyPoints: ['Find all primes up to n', 'Mark multiples of each prime', 'Start marking from p²', 'Segmented sieve for large ranges', 'Linear sieve: O(n) variant'], pseudocode: 'isPrime = [true] * (n+1)\nisPrime[0]=isPrime[1]=false\nfor p in 2..sqrt(n):\n  if isPrime[p]:\n    for mult in p*p..n step p:\n      isPrime[mult] = false\nprimes = [i for i if isPrime[i]]', whenToUse: 'Find all primes, prime factorization, number theory' },
  { title: 'GCD / Euclidean Algorithm', category: 'Math', timeComplexity: 'O(log min(a,b))', spaceComplexity: 'O(1)', keyPoints: ['gcd(a,b) = gcd(b, a%b)', 'Base: gcd(a,0) = a', 'Extended: find x,y where ax+by=gcd', 'LCM = a*b / gcd(a,b)', 'Modular inverse: a*x ≡ 1 (mod m)'], pseudocode: 'def gcd(a, b):\n  while b: a, b = b, a%b\n  return a\n\ndef extgcd(a, b):\n  if b==0: return a, 1, 0\n  g, x, y = extgcd(b, a%b)\n  return g, y, x-(a//b)*y\n\ndef modinv(a, m):\n  g, x, _ = extgcd(a, m)\n  return x%m if g==1 else -1', whenToUse: 'GCD/LCM, modular arithmetic, Diophantine equations' },
  { title: 'Fast Exponentiation', category: 'Math', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', keyPoints: ['Binary exponentiation', 'a^n = (a^(n/2))² if even', 'a^n = a * a^(n-1) if odd', 'With modulo for large numbers', 'Matrix exponentiation for Fibonacci'], pseudocode: 'def power(base, exp, mod):\n  result = 1; base %= mod\n  while exp > 0:\n    if exp%2==1:\n      result = result*base%mod\n    exp >>= 1\n    base = base*base%mod\n  return result\n\n// Matrix expo for Fibonacci\ndef matpow(M, n):\n  result = identity\n  while n>0:\n    if n&1: result=result*M\n    M=M*M; n>>=1\n  return result', whenToUse: 'Large powers with modulo, matrix exponentiation, Fibonacci O(log n)' },
  { title: 'Combinatorics (nCr)', category: 'Math', timeComplexity: 'O(n) precompute', spaceComplexity: 'O(n)', keyPoints: ['nCr = n! / (r! * (n-r)!)', 'Pascal\'s triangle', 'Precompute factorials + modular inverse', 'Lucas theorem for prime mod', 'Stars and bars for distribution'], pseudocode: 'fact=[1]*(n+1)\nfor i in 1..n: fact[i]=fact[i-1]*i%MOD\n\ninvfact=[1]*(n+1)\ninvfact[n]=power(fact[n],MOD-2,MOD)\nfor i in n-1 down to 0:\n  invfact[i]=invfact[i+1]*(i+1)%MOD\n\ndef nCr(n, r):\n  if r<0 or r>n: return 0\n  return fact[n]*invfact[r]%MOD*invfact[n-r]%MOD', whenToUse: 'Counting combinations, probability, paths in grid' },

  // ─── LINKED LIST ──────────────────────────────────────────────────
  { title: 'Linked List Reversal', category: 'Linked List', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', keyPoints: ['Iterative: 3 pointers (prev, curr, next)', 'Recursive: reverse rest, link back', 'Reverse in groups of k', 'Reverse between positions m and n', 'Dummy head simplifies edge cases'], pseudocode: '// Iterative\nprev=null; curr=head\nwhile curr:\n  next=curr.next\n  curr.next=prev\n  prev=curr; curr=next\nreturn prev\n\n// Recursive\ndef reverse(head):\n  if !head or !head.next: return head\n  newHead = reverse(head.next)\n  head.next.next = head\n  head.next = null\n  return newHead', whenToUse: 'Reverse linked list, palindrome check, reverse in k-groups' },
  { title: 'Merge Two Sorted Lists', category: 'Linked List', timeComplexity: 'O(n+m)', spaceComplexity: 'O(1)', keyPoints: ['Dummy head to simplify', 'Compare and attach smaller', 'Attach remaining list', 'Base for merge sort on lists', 'Extend to merge k sorted lists'], pseudocode: 'dummy = new Node(0)\ntail = dummy\nwhile l1 and l2:\n  if l1.val <= l2.val:\n    tail.next=l1; l1=l1.next\n  else:\n    tail.next=l2; l2=l2.next\n  tail=tail.next\ntail.next = l1 or l2\nreturn dummy.next', whenToUse: 'Merge sorted lists, merge sort on lists, K-way merge' },

  // ─── INTERVALS ────────────────────────────────────────────────────
  { title: 'Interval Merge', category: 'Intervals', timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', keyPoints: ['Sort by start time', 'If overlapping: extend end', 'Overlapping: a.end >= b.start', 'Variants: insert interval, remove covered'], pseudocode: 'sort by start\nmerged = [intervals[0]]\nfor interval in intervals[1:]:\n  if interval.start <= merged[-1].end:\n    merged[-1].end = max(\n      merged[-1].end, interval.end)\n  else:\n    merged.append(interval)', whenToUse: 'Merge overlapping intervals, meeting rooms, free time' },
  { title: 'Interval Scheduling', category: 'Intervals', timeComplexity: 'O(n log n)', spaceComplexity: 'O(1)', keyPoints: ['Maximum non-overlapping intervals', 'Sort by END time (greedy)', 'Pick earliest finishing, no overlap', 'Minimum rooms: sort start/end separately'], pseudocode: '// Max non-overlapping\nsort by end time\ncount=1; lastEnd=intervals[0].end\nfor interval in intervals[1:]:\n  if interval.start >= lastEnd:\n    count++; lastEnd=interval.end\n\n// Minimum rooms\nsort starts and ends\nrooms=0; maxRooms=0; i=j=0\nwhile i < n:\n  if starts[i]<ends[j]: rooms++; i++\n  else: rooms--; j++\n  maxRooms = max(maxRooms, rooms)', whenToUse: 'Activity selection, meeting rooms, CPU scheduling' },

  // ─── RANDOMIZED ───────────────────────────────────────────────────
  { title: 'Reservoir Sampling', category: 'Randomized', timeComplexity: 'O(n)', spaceComplexity: 'O(k)', keyPoints: ['Random sample of k items from stream', 'Don\'t know n in advance', 'Each item has k/n probability', 'Replace with decreasing probability'], pseudocode: 'reservoir = first k items\nfor i in k..n-1:\n  j = random(0, i)\n  if j < k:\n    reservoir[j] = stream[i]\nreturn reservoir', whenToUse: 'Random sampling from unknown-size stream, big data' },
];

const categories = ['All', ...Array.from(new Set(CHEAT_ENTRIES.map(e => e.category)))];

const CheatSheet = () => {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All');
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const [expandedIdx, setExpandedIdx] = useState<Set<number>>(new Set());

  const filtered = CHEAT_ENTRIES.filter(e => {
    if (category !== 'All' && e.category !== category) return false;
    if (search && !e.title.toLowerCase().includes(search.toLowerCase()) && !e.keyPoints.some(k => k.toLowerCase().includes(search.toLowerCase()))) return false;
    return true;
  });

  const copyCode = (code: string, idx: number) => {
    navigator.clipboard.writeText(code);
    setCopiedIdx(idx);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const toggleExpand = (idx: number) => {
    setExpandedIdx(prev => {
      const next = new Set(prev);
      if (next.has(idx)) next.delete(idx); else next.add(idx);
      return next;
    });
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="border-b border-panel-border bg-ide-toolbar px-4 py-2 flex items-center gap-3">
        <Button variant="ghost" size="sm" onClick={() => navigate('/modules')} className="h-7 gap-1 text-xs">
          <ArrowLeft className="h-3 w-3" /> Back
        </Button>
        <BookOpen className="h-4 w-4 text-primary" />
        <span className="font-bold text-foreground">DSA Cheat Sheet</span>
        <Badge variant="outline" className="text-[10px]">{CHEAT_ENTRIES.length} algorithms</Badge>
      </div>

      <div className="max-w-5xl mx-auto p-6 space-y-4">
        <div className="flex gap-3 flex-wrap">
          <div className="relative flex-1 min-w-[200px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input className="pl-9" placeholder="Search algorithms..." value={search} onChange={e => setSearch(e.target.value)} />
          </div>
          <div className="flex gap-1 flex-wrap">
            {categories.map(c => (
              <Button key={c} size="sm" variant={category === c ? 'default' : 'outline'} onClick={() => setCategory(c)} className="h-8 text-xs">
                {c}
              </Button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filtered.map((entry, idx) => {
            const isExpanded = expandedIdx.has(idx);
            return (
              <Card key={entry.title} className="overflow-hidden">
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-sm">{entry.title}</CardTitle>
                    <Badge variant="outline" className="text-[9px]">{entry.category}</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Badge className="text-[9px] bg-primary/10 text-primary border-primary/20">⏱ {entry.timeComplexity}</Badge>
                    <Badge className="text-[9px] bg-secondary text-secondary-foreground">💾 {entry.spaceComplexity}</Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-2">
                  <ul className="space-y-0.5">
                    {entry.keyPoints.map((p, i) => (
                      <li key={i} className="text-xs text-muted-foreground">• {p}</li>
                    ))}
                  </ul>
                  
                  <div className="text-[10px] text-primary/80 font-medium">🎯 {entry.whenToUse}</div>

                  <Collapsible open={isExpanded} onOpenChange={() => toggleExpand(idx)}>
                    <CollapsibleTrigger asChild>
                      <Button variant="ghost" size="sm" className="h-6 text-[10px] w-full justify-center text-muted-foreground hover:text-foreground">
                        {isExpanded ? 'Hide Code ▲' : 'Show Pseudocode ▼'}
                      </Button>
                    </CollapsibleTrigger>
                    <CollapsibleContent>
                      <div className="relative">
                        <Button
                          variant="ghost" size="icon"
                          className="absolute top-1 right-1 h-6 w-6"
                          onClick={() => copyCode(entry.pseudocode, idx)}
                        >
                          {copiedIdx === idx ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3 text-muted-foreground" />}
                        </Button>
                        <pre className="bg-secondary/40 rounded p-2 pr-8 text-[10px] font-mono text-foreground overflow-x-auto leading-relaxed">
                          {entry.pseudocode}
                        </pre>
                      </div>
                    </CollapsibleContent>
                  </Collapsible>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default CheatSheet;
